<?php
/**
 * This file is part of CMSGears Framework. Please view License file distributed
 * with the source code for license details.
 *
 * @link https://www.cmsgears.org/
 * @copyright Copyright (c) 2015 VulpineCode Technologies Pvt. Ltd.
 */

// CMG Imports
use cmsgears\core\common\config\CoreGlobal;
use cmsgears\cms\common\config\CmsGlobal;

use cmsgears\core\common\models\entities\Site;
use cmsgears\core\common\models\entities\User;

use cmsgears\core\common\utilities\DateUtil;

/**
 * The breeze cms migration inserts the templates available in Breeze for CMS Module of CMSGears.
 *
 * @since 1.0.0
 */
class m180610_100000_breeze_cms extends \cmsgears\core\common\base\Migration {

	// Public variables

	// Private Variables

	private $cmgPrefix;

	private $site;

	private $master;

	public function init() {

		// Table prefix
		$this->cmgPrefix = Yii::$app->migration->cmgPrefix;

		$this->site		= Site::findBySlug( CoreGlobal::SITE_MAIN );
		$this->master	= User::findByUsername( Yii::$app->migration->getSiteMaster() );

		Yii::$app->core->setSite( $this->site );
	}

    public function up() {

		$this->insertPageTemplates();

		$this->insertFormTemplates();

		$this->insertElementTemplates();
		$this->insertBlockTemplates();

		$this->insertWidgetTemplates();
		$this->insertSidebarTemplates();

		$this->insertMenuTemplates();
    }

	/**
	 * Page Templates
	 */
	private function insertPageTemplates() {

		$master	= $this->master;

		$columns = [ 'createdBy', 'modifiedBy', 'name', 'slug', 'type', 'icon', 'title', 'active', 'frontend', 'description', 'classPath', 'dataPath', 'dataForm', 'attributesPath', 'attributesForm', 'configPath', 'configForm', 'settingsPath', 'settingsForm', 'renderer', 'fileRender', 'layout', 'layoutGroup', 'viewPath', 'view', 'createdAt', 'modifiedAt', 'htmlOptions', 'content', 'data' ];

		$templates = [
			// Page - Default, Landing
			[ $master->id, $master->id, 'Default', CoreGlobal::TEMPLATE_DEFAULT, CmsGlobal::TYPE_PAGE, null, null, true, false, 'Default page layout to display the page.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\PageSettings', '@breeze/templates/cms/page/default/forms', 'default', true, 'page/default', false, '@breeze/templates/cms/page/default', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "page-basic page-default" }', null, '{"tsettings":{"defaultAvatar":"0","lazyAvatar":"0","resAvatar":"0","defaultBanner":"0","lazyBanner":"0","resBanner":"0","fixedBanner":"0","scrollBanner":"0","parallaxBanner":"0","fluidBanner":"0","background":"0","backgroundClass":"","backgroundVideo":null,"texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerInfo":"0","headerContent":"0","headerIconUrl":"","headerFluid":"0","headerBanner":"0","headerGallery":"0","headerScroller":"0","headerElements":"0","headerElementType":"","content":"1","contentTitle":"1","contentInfo":"0","contentSummary":"1","contentData":"1","h1Summary":"0","maxCover":"0","contentSocial":"0","contentLabels":null,"contentAvatar":"0","contentBanner":"1","contentGallery":"0","contentClass":"","contentDataClass":"","styles":"","scripts":"","footer":"0","footerIcon":"0","footerIconClass":null,"footerIconUrl":"","footerTitle":"0","footerTitleData":"","footerInfo":"0","footerInfoData":"","footerContent":"0","footerContentData":"","footerElements":"0","footerElementType":"","metas":"0","metasWithContent":"0","metasOrder":"","metaTypes":"","metaWrapClass":"","elements":"0","elementsBeforeContent":"0","elementsWithContent":"0","elementsOrder":"","elementType":"","boxWrapClass":"","boxWrapper":"","boxClass":"","widgets":"0","widgetsBeforeContent":"0","widgetsWithContent":"0","widgetsOrder":"","widgetType":"","widgetWrapClass":"","widgetWrapper":"","widgetClass":"","blocks":"0","blocksBeforeContent":"0","blocksWithContent":"0","blocksOrder":"","blockType":"","sidebars":"0","sidebarsBeforeContent":"0","sidebarsWithContent":"0","sidebarsOrder":"","sidebarType":"","topSidebar":"0","topSidebarSlugs":"","bottomSidebar":"0","bottomSidebarSlugs":"","leftSidebar":"0","leftSidebarSlug":"","rightSidebar":"1","rightSidebarSlug":"page-right","footerSidebar":"0","footerSidebarSlug":null,"comments":"0","disqus":"0","author":null,"related":null,"popular":null,"similar":null,"purifySummary":"1","purifyContent":"1","amp":"0","ampGoogleScripts":"","ampScriptUrl":"","ampStylePath":"","ampSchema":"","ampMetas":""}}' ],
			[ $master->id, $master->id, 'Landing', CmsGlobal::TEMPLATE_LANDING, CmsGlobal::TYPE_PAGE, null, null, true, false, 'Page layout for home page.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\PageSettings', '@breeze/templates/cms/page/default/forms', 'default', true, 'page/landing', false, '@breeze/templates/cms/page/default', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "page-basic page-default" }', null, '{"tsettings":{"defaultAvatar":"0","lazyAvatar":"0","resAvatar":"0","defaultBanner":"0","lazyBanner":"0","resBanner":"0","fixedBanner":"0","scrollBanner":"0","parallaxBanner":"0","fluidBanner":"0","background":"0","backgroundClass":"","backgroundVideo":null,"texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerInfo":"0","headerContent":"0","headerIconUrl":"","headerFluid":"0","headerBanner":"0","headerGallery":"0","headerScroller":"0","headerElements":"0","headerElementType":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"1","h1Summary":"0","maxCover":"0","contentSocial":"0","contentLabels":null,"contentAvatar":"0","contentBanner":"0","contentGallery":"0","contentClass":"","contentDataClass":"","styles":"","scripts":"","footer":"0","footerIcon":"0","footerIconClass":null,"footerIconUrl":"","footerTitle":"0","footerTitleData":"","footerInfo":"0","footerInfoData":"","footerContent":"0","footerContentData":"","footerElements":"0","footerElementType":"","metas":"0","metasWithContent":"0","metasOrder":"","metaTypes":"","metaWrapClass":"","elements":"0","elementsBeforeContent":"0","elementsWithContent":"0","elementsOrder":"","elementType":"","boxWrapClass":"","boxWrapper":"","boxClass":"","widgets":"0","widgetsBeforeContent":"0","widgetsWithContent":"0","widgetsOrder":"","widgetType":"","widgetWrapClass":"","widgetWrapper":"","widgetClass":"","blocks":"1","blocksBeforeContent":"0","blocksWithContent":"0","blocksOrder":"","blockType":"","sidebars":"0","sidebarsBeforeContent":"0","sidebarsWithContent":"0","sidebarsOrder":"","sidebarType":"","topSidebar":"0","topSidebarSlugs":"","bottomSidebar":"0","bottomSidebarSlugs":"","leftSidebar":"0","leftSidebarSlug":"","rightSidebar":"0","rightSidebarSlug":"","footerSidebar":"0","footerSidebarSlug":null,"comments":"0","disqus":"0","author":null,"related":null,"popular":null,"similar":null,"purifySummary":"1","purifyContent":"1","amp":"0","ampGoogleScripts":"","ampScriptUrl":"","ampStylePath":"","ampSchema":"","ampMetas":""}}' ],
			[ $master->id, $master->id, 'System', CmsGlobal::TEMPLATE_SYSTEM, CmsGlobal::TYPE_PAGE, null, null, true, false, 'Page layout for system pages.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\PageSettings', '@breeze/templates/cms/page/default/forms', 'default', true, 'page/default', false, '@breeze/templates/cms/page/system', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "page-basic page-default" }', null, '{"tsettings":{"defaultAvatar":"0","lazyAvatar":"0","resAvatar":"0","defaultBanner":"0","lazyBanner":"0","resBanner":"0","fixedBanner":"0","scrollBanner":"0","parallaxBanner":"0","fluidBanner":"0","background":"0","backgroundClass":"","backgroundVideo":null,"texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerInfo":"0","headerContent":"0","headerIconUrl":"","headerFluid":"0","headerBanner":"0","headerGallery":"0","headerScroller":"0","headerElements":"0","headerElementType":"","content":"1","contentTitle":"1","contentInfo":"1","contentSummary":"1","contentData":"1","h1Summary":"0","maxCover":"0","contentSocial":"0","contentLabels":null,"contentAvatar":"0","contentBanner":"0","contentGallery":"0","contentClass":"","contentDataClass":"","styles":"","scripts":"","footer":"0","footerIcon":"0","footerIconClass":null,"footerIconUrl":"","footerTitle":"0","footerTitleData":"","footerInfo":"0","footerInfoData":"","footerContent":"0","footerContentData":"","footerElements":"0","footerElementType":"","metas":"0","metasWithContent":"0","metasOrder":"","metaTypes":"","metaWrapClass":"","elements":"0","elementsBeforeContent":"0","elementsWithContent":"0","elementsOrder":"","elementType":"","boxWrapClass":"","boxWrapper":"","boxClass":"","widgets":"0","widgetsBeforeContent":"0","widgetsWithContent":"0","widgetsOrder":"","widgetType":"","widgetWrapClass":"","widgetWrapper":"","widgetClass":"","blocks":"0","blocksBeforeContent":"0","blocksWithContent":"0","blocksOrder":"","blockType":"","sidebars":"0","sidebarsBeforeContent":"0","sidebarsWithContent":"0","sidebarsOrder":"","sidebarType":"","topSidebar":"0","topSidebarSlugs":"","bottomSidebar":"0","bottomSidebarSlugs":"","leftSidebar":"0","leftSidebarSlug":"","rightSidebar":"0","rightSidebarSlug":"","footerSidebar":"0","footerSidebarSlug":null,"comments":"0","disqus":"0","author":null,"related":null,"popular":null,"similar":null,"purifySummary":"1","purifyContent":"1","amp":"0","ampGoogleScripts":"","ampScriptUrl":"","ampStylePath":"","ampSchema":"","ampMetas":""}}' ],
			[ $master->id, $master->id, 'Search', CmsGlobal::TEMPLATE_SEARCH, CmsGlobal::TYPE_PAGE, null, null, true, false, 'Page layout for search pages.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\PageSettings', '@breeze/templates/cms/page/default/forms', 'default', true, 'page/default', false, '@breeze/templates/cms/page/default', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "page-basic page-default" }', null, '{"tsettings":{"defaultAvatar":"0","lazyAvatar":"0","resAvatar":"0","defaultBanner":"0","lazyBanner":"0","resBanner":"0","fixedBanner":"0","scrollBanner":"0","parallaxBanner":"0","fluidBanner":"0","background":"0","backgroundClass":"","backgroundVideo":null,"texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerInfo":"0","headerContent":"0","headerIconUrl":"","headerFluid":"0","headerBanner":"0","headerGallery":"0","headerScroller":"0","headerElements":"0","headerElementType":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"1","h1Summary":"0","maxCover":"0","contentSocial":"0","contentLabels":null,"contentAvatar":"0","contentBanner":"0","contentGallery":"0","contentClass":"","contentDataClass":"","styles":"","scripts":"","footer":"0","footerIcon":"0","footerIconClass":null,"footerIconUrl":"","footerTitle":"0","footerTitleData":"","footerInfo":"0","footerInfoData":"","footerContent":"0","footerContentData":"","footerElements":"0","footerElementType":"","metas":"0","metasWithContent":"0","metasOrder":"","metaTypes":"","metaWrapClass":"","elements":"0","elementsBeforeContent":"0","elementsWithContent":"0","elementsOrder":"","elementType":"","boxWrapClass":"","boxWrapper":"","boxClass":"","widgets":"0","widgetsBeforeContent":"0","widgetsWithContent":"0","widgetsOrder":"","widgetType":"","widgetWrapClass":"","widgetWrapper":"","widgetClass":"","blocks":"0","blocksBeforeContent":"0","blocksWithContent":"0","blocksOrder":"","blockType":"","sidebars":"0","sidebarsBeforeContent":"0","sidebarsWithContent":"0","sidebarsOrder":"","sidebarType":"","topSidebar":"0","topSidebarSlugs":"","bottomSidebar":"0","bottomSidebarSlugs":"","leftSidebar":"0","leftSidebarSlug":"","rightSidebar":"0","rightSidebarSlug":"","footerSidebar":"0","footerSidebarSlug":null,"comments":"0","disqus":"0","author":null,"related":null,"popular":null,"similar":null,"purifySummary":"1","purifyContent":"1","amp":"0","ampGoogleScripts":"","ampScriptUrl":"","ampStylePath":"","ampSchema":"","ampMetas":""}}' ],
			[ $master->id, $master->id, 'QnA', CmsGlobal::TEMPLATE_QNA, CmsGlobal::TYPE_PAGE, null, 'Questions and Answers', true, false, 'Page layout for pages having Questions and Answers accordian using page attributes.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\PageSettings', '@breeze/templates/cms/page/default/forms', 'default', true, 'page/default', false, '@breeze/templates/cms/page/qna', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "page-basic page-default" }', null, '{"tsettings":{"defaultAvatar":"0","lazyAvatar":"0","resAvatar":"0","defaultBanner":"0","lazyBanner":"0","resBanner":"0","fixedBanner":"0","scrollBanner":"0","parallaxBanner":"0","fluidBanner":"0","background":"0","backgroundClass":"","backgroundVideo":null,"texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerInfo":"0","headerContent":"0","headerIconUrl":"","headerFluid":"0","headerBanner":"0","headerGallery":"0","headerScroller":"0","headerElements":"0","headerElementType":"","content":"1","contentTitle":"1","contentInfo":"1","contentSummary":"1","contentData":"1","h1Summary":"0","maxCover":"0","contentSocial":"0","contentLabels":null,"contentAvatar":"0","contentBanner":"1","contentGallery":"0","contentClass":"","contentDataClass":"","styles":"","scripts":"","footer":"0","footerIcon":"0","footerIconClass":null,"footerIconUrl":"","footerTitle":"0","footerTitleData":"","footerInfo":"0","footerInfoData":"","footerContent":"0","footerContentData":"","footerElements":"0","footerElementType":"","metas":"1","metasWithContent":"1","metasOrder":"","metaTypes":"","metaWrapClass":"","elements":"0","elementsBeforeContent":"0","elementsWithContent":"0","elementsOrder":"","elementType":"","boxWrapClass":"","boxWrapper":"","boxClass":"","widgets":"0","widgetsBeforeContent":"0","widgetsWithContent":"0","widgetsOrder":"","widgetType":"","widgetWrapClass":"","widgetWrapper":"","widgetClass":"","blocks":"0","blocksBeforeContent":"0","blocksWithContent":"0","blocksOrder":"","blockType":"","sidebars":"0","sidebarsBeforeContent":"0","sidebarsWithContent":"0","sidebarsOrder":"","sidebarType":"","topSidebar":"0","topSidebarSlugs":"","bottomSidebar":"0","bottomSidebarSlugs":"","leftSidebar":"0","leftSidebarSlug":"","rightSidebar":"1","rightSidebarSlug":"page-right","footerSidebar":"0","footerSidebarSlug":null,"comments":"0","disqus":"0","author":null,"related":null,"popular":null,"similar":null,"purifySummary":"1","purifyContent":"1","amp":"0","ampGoogleScripts":"","ampScriptUrl":"","ampStylePath":"","ampSchema":"","ampMetas":""}}' ],
			[ $master->id, $master->id, 'Blog', CmsGlobal::TEMPLATE_BLOG, CmsGlobal::TYPE_PAGE, null, null, true, false, 'Page layout to show blog posts on blog page.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\PageSettings', '@breeze/templates/cms/page/default/forms', 'default', true, 'page/default', false, '@breeze/templates/cms/page/search', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "page-basic page-default" }', null, '{"tsettings":{"defaultAvatar":"0","lazyAvatar":"0","resAvatar":"0","defaultBanner":"0","lazyBanner":"0","resBanner":"0","fixedBanner":"0","scrollBanner":"0","parallaxBanner":"0","fluidBanner":"0","background":"0","backgroundClass":"","backgroundVideo":null,"texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerInfo":"0","headerContent":"0","headerIconUrl":"","headerFluid":"0","headerBanner":"0","headerGallery":"0","headerScroller":"0","headerElements":"0","headerElementType":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"1","h1Summary":"0","maxCover":"0","contentSocial":"0","contentLabels":null,"contentAvatar":"0","contentBanner":"0","contentGallery":"0","contentClass":"","contentDataClass":"","styles":"","scripts":"","footer":"0","footerIcon":"0","footerIconClass":null,"footerIconUrl":"","footerTitle":"0","footerTitleData":"","footerInfo":"0","footerInfoData":"","footerContent":"0","footerContentData":"","footerElements":"0","footerElementType":"","metas":"0","metasWithContent":"0","metasOrder":"","metaTypes":"","metaWrapClass":"","elements":"0","elementsBeforeContent":"0","elementsWithContent":"0","elementsOrder":"","elementType":"","boxWrapClass":"","boxWrapper":"","boxClass":"","widgets":"0","widgetsBeforeContent":"0","widgetsWithContent":"0","widgetsOrder":"","widgetType":"","widgetWrapClass":"","widgetWrapper":"","widgetClass":"","blocks":"0","blocksBeforeContent":"0","blocksWithContent":"0","blocksOrder":"","blockType":"","sidebars":"0","sidebarsBeforeContent":"0","sidebarsWithContent":"0","sidebarsOrder":"","sidebarType":"","topSidebar":"0","topSidebarSlugs":"","bottomSidebar":"0","bottomSidebarSlugs":"","leftSidebar":"0","leftSidebarSlug":"","rightSidebar":"0","rightSidebarSlug":"","footerSidebar":"0","footerSidebarSlug":null,"comments":"0","disqus":"0","author":null,"related":null,"popular":null,"similar":null,"purifySummary":"1","purifyContent":"1","amp":"0","ampGoogleScripts":"","ampScriptUrl":"","ampStylePath":"","ampSchema":"","ampMetas":""}}' ],
			[ $master->id, $master->id, 'Articles', CmsGlobal::TEMPLATE_ARTICLE, CmsGlobal::TYPE_PAGE, null, null, true, false, 'Page layout to show blog posts on blog page.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\PageSettings', '@breeze/templates/cms/page/default/forms', 'default', true, 'page/default', false, '@breeze/templates/cms/page/search', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "page-basic page-default" }', null, '{"tsettings":{"defaultAvatar":"0","lazyAvatar":"0","resAvatar":"0","defaultBanner":"0","lazyBanner":"0","resBanner":"0","fixedBanner":"0","scrollBanner":"0","parallaxBanner":"0","fluidBanner":"0","background":"0","backgroundClass":"","backgroundVideo":null,"texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerInfo":"0","headerContent":"0","headerIconUrl":"","headerFluid":"0","headerBanner":"0","headerGallery":"0","headerScroller":"0","headerElements":"0","headerElementType":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"1","h1Summary":"0","maxCover":"0","contentSocial":"0","contentLabels":null,"contentAvatar":"0","contentBanner":"0","contentGallery":"0","contentClass":"","contentDataClass":"","styles":"","scripts":"","footer":"0","footerIcon":"0","footerIconClass":null,"footerIconUrl":"","footerTitle":"0","footerTitleData":"","footerInfo":"0","footerInfoData":"","footerContent":"0","footerContentData":"","footerElements":"0","footerElementType":"","metas":"0","metasWithContent":"0","metasOrder":"","metaTypes":"","metaWrapClass":"","elements":"0","elementsBeforeContent":"0","elementsWithContent":"0","elementsOrder":"","elementType":"","boxWrapClass":"","boxWrapper":"","boxClass":"","widgets":"0","widgetsBeforeContent":"0","widgetsWithContent":"0","widgetsOrder":"","widgetType":"","widgetWrapClass":"","widgetWrapper":"","widgetClass":"","blocks":"0","blocksBeforeContent":"0","blocksWithContent":"0","blocksOrder":"","blockType":"","sidebars":"0","sidebarsBeforeContent":"0","sidebarsWithContent":"0","sidebarsOrder":"","sidebarType":"","topSidebar":"0","topSidebarSlugs":"","bottomSidebar":"0","bottomSidebarSlugs":"","leftSidebar":"0","leftSidebarSlug":"","rightSidebar":"0","rightSidebarSlug":"","footerSidebar":"0","footerSidebarSlug":null,"comments":"0","disqus":"0","author":null,"related":null,"popular":null,"similar":null,"purifySummary":"1","purifyContent":"1","amp":"0","ampGoogleScripts":"","ampScriptUrl":"","ampStylePath":"","ampSchema":"","ampMetas":""}}' ],
			// Article - Default
			[ $master->id, $master->id, 'Default', CoreGlobal::TEMPLATE_DEFAULT, CmsGlobal::TYPE_ARTICLE, null, null, true, true, 'Default article layout for single article.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\PageSettings', '@breeze/templates/cms/page/default/forms', 'default', true, 'article/default', false, '@breeze/templates/cms/article/default', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "page-basic page-default" }', null, '{"tsettings":{"defaultAvatar":"0","lazyAvatar":"0","resAvatar":"0","defaultBanner":"0","lazyBanner":"0","resBanner":"0","fixedBanner":"0","scrollBanner":"0","parallaxBanner":"0","fluidBanner":"0","background":"0","backgroundClass":"","backgroundVideo":null,"texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerInfo":"0","headerContent":"0","headerIconUrl":"","headerFluid":"0","headerBanner":"0","headerGallery":"0","headerScroller":"0","headerElements":"0","headerElementType":"","content":"1","contentTitle":"1","contentInfo":"1","contentSummary":"1","contentData":"1","h1Summary":"0","maxCover":"0","contentSocial":"1","contentLabels":null,"contentAvatar":"0","contentBanner":"1","contentGallery":"0","contentClass":"","contentDataClass":"","styles":"","scripts":"","footer":"0","footerIcon":"0","footerIconClass":null,"footerIconUrl":"","footerTitle":"0","footerTitleData":"","footerInfo":"0","footerInfoData":"","footerContent":"0","footerContentData":"","footerElements":"0","footerElementType":"","metas":"0","metasWithContent":"0","metasOrder":"","metaTypes":"","metaWrapClass":"","elements":"0","elementsBeforeContent":"0","elementsWithContent":"0","elementsOrder":"","elementType":"","boxWrapClass":"","boxWrapper":"","boxClass":"","widgets":"0","widgetsBeforeContent":"0","widgetsWithContent":"0","widgetsOrder":"","widgetType":"","widgetWrapClass":"","widgetWrapper":"","widgetClass":"","blocks":"0","blocksBeforeContent":"0","blocksWithContent":"0","blocksOrder":"","blockType":"","sidebars":"0","sidebarsBeforeContent":"0","sidebarsWithContent":"0","sidebarsOrder":"","sidebarType":"","topSidebar":"0","topSidebarSlugs":"","bottomSidebar":"0","bottomSidebarSlugs":"","leftSidebar":"0","leftSidebarSlug":"","rightSidebar":"1","rightSidebarSlug":"article-right","footerSidebar":"0","footerSidebarSlug":null,"comments":"0","disqus":"0","author":null,"related":null,"popular":null,"similar":null,"purifySummary":"1","purifyContent":"1","amp":"0","ampGoogleScripts":"","ampScriptUrl":"","ampStylePath":"","ampSchema":"","ampMetas":"","metaType":""}}' ],
			[ $master->id, $master->id, 'Editor', CmsGlobal::TEMPLATE_EDITOR, CmsGlobal::TYPE_ARTICLE, null, null, true, false, 'Default article layout for single article.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\PageSettings', '@breeze/templates/cms/page/default/forms', 'default', true, 'article/default', false, '@breeze/templates/cms/article/default', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "page-basic page-default" }', null, null ],
			[ $master->id, $master->id, 'Author', CmsGlobal::TEMPLATE_AUTHOR, CmsGlobal::TYPE_ARTICLE, null, null, true, false, 'Article layout for author articles.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\PageSettings', '@breeze/templates/cms/page/default/forms', 'default', true, 'article/default', false, '@breeze/templates/cms/article/default', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "page-basic page-default" }', null, null ],
			[ $master->id, $master->id, 'Archive', CmsGlobal::TEMPLATE_ARCHIVE, CmsGlobal::TYPE_ARTICLE, null, null, true, false, 'Article layout for archive articles.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\PageSettings', '@breeze/templates/cms/page/default/forms', 'default', true, 'article/default', false, '@breeze/templates/cms/article/default', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "page-basic page-default" }', null, null ],
			// Post - Default
			[ $master->id, $master->id, 'Default', CoreGlobal::TEMPLATE_DEFAULT, CmsGlobal::TYPE_POST, null, null, true, true, 'Default post layout for single blog post.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\PageSettings', '@breeze/templates/cms/post/default/forms', 'default', true, 'post/default', true, '@breeze/templates/cms/post/default', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "page-basic page-default" }', null, '{"tsettings":{"defaultAvatar":"0","lazyAvatar":"0","resAvatar":"0","defaultBanner":"0","lazyBanner":"0","resBanner":"0","fixedBanner":"0","scrollBanner":"0","parallaxBanner":"0","fluidBanner":"0","background":"0","backgroundClass":"","backgroundVideo":null,"texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerInfo":"0","headerContent":"0","headerIconUrl":"","headerFluid":"0","headerBanner":"0","headerGallery":"0","headerScroller":"0","headerElements":"0","headerElementType":"","content":"1","contentTitle":"1","contentInfo":"1","contentSummary":"1","contentData":"1","h1Summary":"0","maxCover":"0","contentSocial":"1","contentLabels":"1","contentAvatar":"0","contentBanner":"1","contentGallery":"0","contentClass":"","contentDataClass":"","styles":"","scripts":"","footer":"0","footerIcon":"0","footerIconClass":null,"footerIconUrl":"","footerTitle":"0","footerTitleData":"","footerInfo":"0","footerInfoData":"","footerContent":"0","footerContentData":"","footerElements":"0","footerElementType":"","metas":"0","metasWithContent":"0","metasOrder":"","metaTypes":"","metaWrapClass":"","elements":"0","elementsBeforeContent":"0","elementsWithContent":"0","elementsOrder":"","elementType":"","boxWrapClass":"","boxWrapper":"","boxClass":"","widgets":"0","widgetsBeforeContent":"0","widgetsWithContent":"0","widgetsOrder":"","widgetType":"","widgetWrapClass":"","widgetWrapper":"","widgetClass":"","blocks":"0","blocksBeforeContent":"0","blocksWithContent":"0","blocksOrder":"","blockType":"","sidebars":"0","sidebarsBeforeContent":"0","sidebarsWithContent":"0","sidebarsOrder":"","sidebarType":"","topSidebar":"1","topSidebarSlugs":"post-top","bottomSidebar":"0","bottomSidebarSlugs":"","leftSidebar":"0","leftSidebarSlug":"","rightSidebar":"1","rightSidebarSlug":"post-right","footerSidebar":"0","footerSidebarSlug":null,"comments":"1","disqus":"0","author":"0","related":"0","popular":"0","similar":"0","purifySummary":"1","purifyContent":"1","amp":"0","ampGoogleScripts":"","ampScriptUrl":"","ampStylePath":"","ampSchema":"","ampMetas":""}}' ],
			[ $master->id, $master->id, 'Editor', CmsGlobal::TEMPLATE_EDITOR, CmsGlobal::TYPE_POST, null, null, true, false, 'Default post layout for single blog post.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\PageSettings', '@breeze/templates/cms/post/default/forms', 'default', true, 'post/default', true, '@breeze/templates/cms/post/default', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "page-basic page-default" }', null, null ],
			[ $master->id, $master->id, 'Category', CmsGlobal::TEMPLATE_CATEGORY, CmsGlobal::TYPE_POST, null, null, true, false, 'Post layout for category posts.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\PageSettings', '@breeze/templates/cms/post/default/forms', 'default', true, 'post/default', true, '@breeze/templates/cms/post/default', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "page-basic page-default" }', null, null ],
			[ $master->id, $master->id, 'Tag', CmsGlobal::TEMPLATE_TAG, CmsGlobal::TYPE_POST, null, null, true, false, 'Post layout for tag posts.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\PageSettings', '@breeze/templates/cms/post/default/forms', 'default', true, 'post/default', true, '@breeze/templates/cms/post/default', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "page-basic page-default" }', null, null ],
			[ $master->id, $master->id, 'Author', CmsGlobal::TEMPLATE_AUTHOR, CmsGlobal::TYPE_POST, null, null, true, false, 'Post layout for author posts.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\PageSettings', '@breeze/templates/cms/post/default/forms', 'default', true, 'post/default', true, '@breeze/templates/cms/post/default', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "page-basic page-default" }', null, null ],
			[ $master->id, $master->id, 'Archive', CmsGlobal::TEMPLATE_ARCHIVE, CmsGlobal::TYPE_POST, null, null, true, false, 'Post layout for archive posts.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\PageSettings', '@breeze/templates/cms/post/default/forms', 'default', true, 'post/default', true, '@breeze/templates/cms/post/default', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "page-basic page-default" }', null, null ]
		];

		$this->batchInsert( $this->cmgPrefix . 'core_template', $columns, $templates );
	}

	/**
	 * Form Templates
	 */
	private function insertFormTemplates() {

		$master	= $this->master;

		$columns = [ 'createdBy', 'modifiedBy', 'name', 'slug', 'type', 'icon', 'title', 'active', 'frontend', 'description', 'classPath', 'dataPath', 'dataForm', 'attributesPath', 'attributesForm', 'configPath', 'configForm', 'settingsPath', 'settingsForm', 'renderer', 'fileRender', 'layout', 'layoutGroup', 'viewPath', 'view', 'createdAt', 'modifiedAt', 'htmlOptions', 'content', 'data' ];

		$templates = [
			// Form - Default
			[ $master->id, $master->id, 'Default', CoreGlobal::TEMPLATE_DEFAULT, CoreGlobal::TYPE_FORM, null, null, true, false, 'It can be used to display public forms.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\FormSettings', '@breeze/templates/cms/form/default/forms', 'default', true, 'form/default', false, '@breeze/templates/cms/form/default', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "page-basic page-default" }', null, null ],
			[ $master->id, $master->id, 'Contact', 'contact', CoreGlobal::TYPE_FORM, null, null, true, false, 'It can be used to display contact forms.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\FormSettings', '@breeze/templates/cms/form/default/forms', 'default', true, 'form/default', false, '@breeze/templates/cms/form/default', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "page-basic page-default" }', null, null ],
			[ $master->id, $master->id, 'Feedback', 'feedback', CoreGlobal::TYPE_FORM, null, null, true, false, 'It can be used to display feedback forms.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\FormSettings', '@breeze/templates/cms/form/default/forms', 'default', true, 'form/default', false, '@breeze/templates/cms/form/default', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "page-basic page-default" }', null, null ],
			[ $master->id, $master->id, 'Testimonial', 'testimonial', CoreGlobal::TYPE_FORM, null, null, true, false, 'It can be used to display testimonial forms.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\FormSettings', '@breeze/templates/cms/form/default/forms', 'default', true, 'form/default', false, '@breeze/templates/cms/form/default', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "page-basic page-default" }', null, null ]
		];

		$this->batchInsert( $this->cmgPrefix . 'core_template', $columns, $templates );
	}

	/**
	 * Element Templates
	 */
	private function insertElementTemplates() {

		$site	= $this->site;
		$master	= $this->master;

		$columns = [ 'createdBy', 'modifiedBy', 'name', 'slug', 'type', 'icon', 'title', 'active', 'frontend', 'description', 'classPath', 'dataPath', 'dataForm', 'attributesPath', 'attributesForm', 'configPath', 'configForm', 'settingsPath', 'settingsForm', 'renderer', 'fileRender', 'layout', 'layoutGroup', 'viewPath', 'view', 'createdAt', 'modifiedAt', 'htmlOptions', 'content', 'data' ];

		$templates = [
			// Element - Card
			[ $master->id, $master->id, 'Card', 'card', CmsGlobal::TYPE_ELEMENT, null, null, true, true, 'Default layout for card elements.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\ElementSettings', '@breeze/templates/cms/element/card/default/forms', 'default', true, null, false, '@breeze/templates/cms/element/card/default', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "card card-basic card-default" }', null, '{"tsettings":{"defaultAvatar":"0","lazyAvatar":"0","resAvatar":"0","defaultBanner":"0","lazyBanner":"0","resBanner":"0","bkg":"0","bkgClass":"","bkgVideo":"0","texture":"0","header":"1","headerIcon":"1","headerTitle":"1","headerInfo":"1","headerContent":"1","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"1","contentRaw":"","maxCover":"0","contentClass":"","contentDataClass":"","styles":"","scripts":"","footer":"0","footerIcon":"0","footerIconClass":null,"footerIconUrl":"","footerTitle":"0","footerTitleData":"","footerInfo":"0","footerInfoData":"","footerContent":"0","footerContentData":"","metas":"0","metaTypes":"","metaWrapClass":"","purifySummary":"1","purifyContent":"1"}}' ],
			[ $master->id, $master->id, 'Card Text', 'card-text', CmsGlobal::TYPE_ELEMENT, null, null, true, false, 'Default layout for card element showing text.', null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\element\card\TextConfig', '@breeze/templates/cms/element/card/text/forms', 'cmsgears\templates\breeze\models\cms\settings\ElementSettings', '@breeze/templates/cms/element/card/default/forms', 'default', true, null, false, '@breeze/templates/cms/element/card/text', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "card card-basic card-default card-text card-text-regular" }', null, '{"tsettings":{"defaultAvatar":"0","lazyAvatar":"0","resAvatar":"0","defaultBanner":"0","lazyBanner":"0","resBanner":"0","bkg":"0","bkgClass":"","bkgVideo":"0","texture":"0","header":"1","headerIcon":"1","headerTitle":"1","headerInfo":"1","headerContent":"1","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"1","contentRaw":"","maxCover":"0","contentClass":"","contentDataClass":"","styles":"","scripts":"","footer":"0","footerIcon":"0","footerIconClass":null,"footerIconUrl":"","footerTitle":"0","footerTitleData":"","footerInfo":"0","footerInfoData":"","footerContent":"0","footerContentData":"","metas":"0","metaTypes":"","metaWrapClass":"","purifySummary":"1","purifyContent":"1"}}' ],
			[ $master->id, $master->id, 'Card Social', 'card-social', CmsGlobal::TYPE_ELEMENT, null, null, true, false, 'Default layout for card element showing its social attributes.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\ElementSettings', '@breeze/templates/cms/element/card/default/forms', 'default', true, null, false, '@breeze/templates/cms/element/card/social', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "card card-basic card-default card-social card-social-regular" }', null, '{"tsettings":{"defaultAvatar":"0","lazyAvatar":"0","resAvatar":"0","defaultBanner":"0","lazyBanner":"0","resBanner":"0","bkg":"0","bkgClass":"","bkgVideo":"0","texture":"0","header":"1","headerIcon":"1","headerTitle":"1","headerInfo":"1","headerContent":"1","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"1","contentRaw":"","maxCover":"0","contentClass":"","contentDataClass":"","styles":"","scripts":"","footer":"0","footerIcon":"0","footerIconClass":null,"footerIconUrl":"","footerTitle":"0","footerTitleData":"","footerInfo":"0","footerInfoData":"","footerContent":"0","footerContentData":"","metas":"1","metaTypes":"social","metaWrapClass":"menu-social","purifySummary":"1","purifyContent":"1"}}' ],
			[ $master->id, $master->id, 'Card Gallery', 'card-gallery', CmsGlobal::TYPE_ELEMENT, null, null, true, false, "Default layout for card elements showing it's gallery.", null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\element\card\GalleryConfig', '@breeze/templates/cms/element/card/gallery/forms', 'cmsgears\templates\breeze\models\cms\settings\ElementSettings', '@breeze/templates/cms/element/card/default/forms', 'default', true, null, false, '@breeze/templates/cms/element/card/gallery', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "card card-basic card-default card-gallery card-gallery-regular" }', null, null ],
			[ $master->id, $master->id, 'Card Slider', 'card-slider', CmsGlobal::TYPE_ELEMENT, null, null, true, false, "Default layout for card elements showing slider of it's gallery.", null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\element\card\SliderConfig', '@breeze/templates/cms/element/card/slider/gallery/forms', 'cmsgears\templates\breeze\models\cms\settings\ElementSettings', '@breeze/templates/cms/element/card/default/forms', 'default', true, null, false, '@breeze/templates/cms/element/card/slider', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "card card-basic card-default card-slider card-slider-regular" }', null, null ],
			[ $master->id, $master->id, 'Card Attributes Slider', 'card-attributes-slider', CmsGlobal::TYPE_ELEMENT, null, null, true, false, "Default layout for card elements showing slider of it's attributes.", null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\ElementSettings', '@breeze/templates/cms/element/card/default/forms', 'default', true, null, false, '@breeze/templates/cms/element/card/attribute/slider', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "card card-basic card-default card-attributes-slider card-attributes-slider-regular" }', null, null ],
			[ $master->id, $master->id, 'Card Attributes Accordian', 'card-attributes-accordian', CmsGlobal::TYPE_ELEMENT, null, null, true, false, "Default layout for card elements showing accordian of it's attributes.", null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\ElementSettings', '@breeze/templates/cms/element/card/default/forms', 'default', true, null, false, '@breeze/templates/cms/element/card/attribute/accordian', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "card card-basic card-default card-attributes-accordian card-attributes-accordian-regular" }', null, null ],
			[ $master->id, $master->id, 'Card Form', 'card-form', CmsGlobal::TYPE_ELEMENT, null, null, true, false, 'Default layout for card elements having Ajax form.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\ElementSettings', '@breeze/templates/cms/element/card/default/forms', 'default', true, null, false, '@breeze/templates/cms/element/card/form', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "card card-basic card-default card-form card-form-regular" }', null, null ],
			// Element - Box
			[ $master->id, $master->id, 'Box', 'box', CmsGlobal::TYPE_ELEMENT, null, null, true, true, 'Default layout for box elements.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\ElementSettings', '@breeze/templates/cms/element/box/default/forms', 'default', true, null, false, '@breeze/templates/cms/element/box/default', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "box box-basic box-default" }', null, '{"tsettings":{"defaultAvatar":"0","lazyAvatar":"0","resAvatar":"0","defaultBanner":"0","lazyBanner":"0","resBanner":"0","bkg":"0","bkgClass":"","bkgVideo":"0","texture":"0","header":"1","headerIcon":"1","headerTitle":"1","headerInfo":"1","headerContent":"1","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"1","contentRaw":"","maxCover":"0","contentClass":"","contentDataClass":"","styles":"","scripts":"","footer":"0","footerIcon":"0","footerIconClass":null,"footerIconUrl":"","footerTitle":"0","footerTitleData":"","footerInfo":"0","footerInfoData":"","footerContent":"0","footerContentData":"","metas":"0","metaTypes":"","metaWrapClass":"","purifySummary":"1","purifyContent":"1"}}' ],
			[ $master->id, $master->id, 'Box Text', 'box-text', CmsGlobal::TYPE_ELEMENT, null, null, true, false, 'Default layout for box element showing text.', null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\element\box\TextConfig', '@breeze/templates/cms/element/box/text/forms', 'cmsgears\templates\breeze\models\cms\settings\ElementSettings', '@breeze/templates/cms/element/box/default/forms', 'default', true, null, false, '@breeze/templates/cms/element/box/text', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "box box-basic box-default box-text box-text-regular" }', null, '{"tsettings":{"defaultAvatar":"0","lazyAvatar":"0","resAvatar":"0","defaultBanner":"0","lazyBanner":"0","resBanner":"0","bkg":"0","bkgClass":"","bkgVideo":"0","texture":"0","header":"1","headerIcon":"1","headerTitle":"1","headerInfo":"1","headerContent":"1","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"1","contentRaw":"","maxCover":"0","contentClass":"","contentDataClass":"","styles":"","scripts":"","footer":"0","footerIcon":"0","footerIconClass":null,"footerIconUrl":"","footerTitle":"0","footerTitleData":"","footerInfo":"0","footerInfoData":"","footerContent":"0","footerContentData":"","metas":"0","metaTypes":"","metaWrapClass":"","purifySummary":"1","purifyContent":"1"}}' ],
			[ $master->id, $master->id, 'Box Social', 'box-social', CmsGlobal::TYPE_ELEMENT, null, null, true, false, 'Default layout for box element showing its social attributes.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\ElementSettings', '@breeze/templates/cms/element/box/default/forms', 'default', true, null, false, '@breeze/templates/cms/element/box/social', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "box box-basic box-default box-social box-social-regular" }', null, '{"tsettings":{"defaultAvatar":"0","lazyAvatar":"0","resAvatar":"0","defaultBanner":"0","lazyBanner":"0","resBanner":"0","bkg":"0","bkgClass":"","bkgVideo":"0","texture":"0","header":"1","headerIcon":"1","headerTitle":"1","headerInfo":"1","headerContent":"1","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"1","contentRaw":"","maxCover":"0","contentClass":"","contentDataClass":"","styles":"","scripts":"","footer":"0","footerIcon":"0","footerIconClass":null,"footerIconUrl":"","footerTitle":"0","footerTitleData":"","footerInfo":"0","footerInfoData":"","footerContent":"0","footerContentData":"","metas":"1","metaTypes":"social","metaWrapClass":"menu-social","purifySummary":"1","purifyContent":"1"}}' ],
			[ $master->id, $master->id, 'Box Gallery', 'box-gallery', CmsGlobal::TYPE_ELEMENT, null, null, true, false, "Default layout for box elements showing it's gallery.", null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\element\box\GalleryConfig', '@breeze/templates/cms/element/box/gallery/forms', 'cmsgears\templates\breeze\models\cms\settings\ElementSettings', '@breeze/templates/cms/element/box/default/forms', 'default', true, null, false, '@breeze/templates/cms/element/box/gallery', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "box box-basic box-default box-gallery box-gallery-regular" }', null, null ],
			[ $master->id, $master->id, 'Box Slider', 'box-slider', CmsGlobal::TYPE_ELEMENT, null, null, true, false, "Default layout for box elements showing slider of it's gallery.", null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\element\box\SliderConfig', '@breeze/templates/cms/element/box/slider/gallery/forms', 'cmsgears\templates\breeze\models\cms\settings\ElementSettings', '@breeze/templates/cms/element/box/default/forms', 'default', true, null, false, '@breeze/templates/cms/element/box/slider', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "box box-basic box-default box-slider box-slider-regular" }', null, null ],
			[ $master->id, $master->id, 'Box Attributes Slider', 'box-attributes-slider', CmsGlobal::TYPE_ELEMENT, null, null, true, false, "Default layout for box elements showing slider of it's attributes.", null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\ElementSettings', '@breeze/templates/cms/element/box/default/forms', 'default', true, null, false, '@breeze/templates/cms/element/box/attribute/slider', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "box box-basic box-default box-slider box-attributes-slider box-attributes-slider-regular"}', null, null ],
			[ $master->id, $master->id, 'Box Attributes Accordian', 'box-attributes-accordian', CmsGlobal::TYPE_ELEMENT, null, null, true, false, "Default layout for box elements showing accordian of it's attributes.", null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\ElementSettings', '@breeze/templates/cms/element/box/default/forms', 'default', true, null, false, '@breeze/templates/cms/element/box/attribute/accordian', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "box box-basic box-default box-attributes-accordian box-attributes-accordian-regular" }', null, null ],
			[ $master->id, $master->id, 'Box Form', 'box-form', CmsGlobal::TYPE_ELEMENT, null, null, true, false, 'Default layout for box elements having Ajax form.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\ElementSettings', '@breeze/templates/cms/element/box/default/forms', 'default', true, null, false, '@breeze/templates/cms/element/box/form', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "box box-basic box-default box-form box-form-regular" }', null, null ],
			// Element - ZigZag
			[ $master->id, $master->id, 'ZigZag', 'zigzag', CmsGlobal::TYPE_ELEMENT, null, null, true, false, 'Default layout for elements arranged in zigzag fashion using ZigZag Block.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\ElementSettings', '@breeze/templates/cms/element/box/default/forms', 'default', true, null, false, '@breeze/templates/cms/element/zigzag', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "box box-basic box-zigzag box-zigzag-regular row data-zigzag-row" }', null, '{"tsettings":{"defaultAvatar":"0","lazyAvatar":"0","resAvatar":"0","defaultBanner":"0","lazyBanner":"0","resBanner":"0","bkg":"0","bkgClass":"","bkgVideo":"0","texture":"0","header":"1","headerIcon":"1","headerTitle":"1","headerInfo":"1","headerContent":"1","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"1","contentRaw":"","maxCover":"0","contentClass":"","contentDataClass":"reader","styles":"","scripts":"","footer":"0","footerIcon":"0","footerIconClass":null,"footerIconUrl":"","footerTitle":"0","footerTitleData":"","footerInfo":"0","footerInfoData":"","footerContent":"0","footerContentData":"","metas":"0","metaTypes":"","metaWrapClass":"","purifySummary":"1","purifyContent":"1"}}' ]
		];

		$this->batchInsert( $this->cmgPrefix . 'core_template', $columns, $templates );
	}

	/**
	 * Block Templates
	 */
	private function insertBlockTemplates() {

		$site	= $this->site;
		$master	= $this->master;

		$columns = [ 'createdBy', 'modifiedBy', 'name', 'slug', 'type', 'icon', 'title', 'active', 'frontend', 'description', 'classPath', 'dataPath', 'dataForm', 'attributesPath', 'attributesForm', 'configPath', 'configForm', 'settingsPath', 'settingsForm', 'renderer', 'fileRender', 'layout', 'layoutGroup', 'viewPath', 'view', 'createdAt', 'modifiedAt', 'htmlOptions', 'content', 'data' ];

		$templates = [
			// Block - Default
			[ $master->id, $master->id, 'Default', CoreGlobal::TEMPLATE_DEFAULT, CmsGlobal::TYPE_BLOCK, null, null, true, true, 'Default layout for blocks.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\BlockSettings', '@breeze/templates/cms/block/default/forms', 'default', true, null, false, '@breeze/templates/cms/block/default', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "block block-basic block-default" }', null, null ],
			// Max Block - Default, Testimonial, FoxSlider
			[ $master->id, $master->id, 'Max', 'max', CmsGlobal::TYPE_BLOCK, null, null, true, false, 'Default layout for max blocks.', null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\block\MaxConfig', '@breeze/templates/cms/block/max/forms', 'cmsgears\templates\breeze\models\cms\settings\BlockSettings', '@breeze/templates/cms/block/default/forms', 'default', true, null, false, '@breeze/templates/cms/block/default', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "cmt-block block block-max" }', null, null ],
			[ $master->id, $master->id, 'Text', 'text', CmsGlobal::TYPE_BLOCK, null, null, true, false, 'Default layout for block showing text.', null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\block\TextConfig', '@breeze/templates/cms/block/text/forms', 'cmsgears\templates\breeze\models\cms\settings\BlockSettings', '@breeze/templates/cms/block/default/forms', 'default', true, null, false, '@breeze/templates/cms/block/text', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "cmt-block block block-max block-text block-text-regular" }', null, '{"tsettings":{"defaultAvatar":"0","lazyAvatar":"0","resAvatar":"0","defaultBanner":"0","lazyBanner":"0","resBanner":"0","bkg":"0","bkgClass":"","bkgVideo":"0","texture":"0","header":"1","headerIcon":"1","headerTitle":"1","headerInfo":"1","headerContent":"1","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"1","contentRaw":"","maxCover":"0","contentClass":"","contentDataClass":"","styles":"","scripts":"","footer":"0","footerIcon":"0","footerIconClass":null,"footerIconUrl":"","footerTitle":"0","footerTitleData":"","footerInfo":"0","footerInfoData":"","footerContent":"0","footerContentData":"","metas":"0","metaTypes":"","metaWrapClass":"","purifySummary":"1","purifyContent":"1"}}' ],
			[ $master->id, $master->id, 'Social', CmsGlobal::TEMPLATE_SOCIAL, CmsGlobal::TYPE_BLOCK, null, null, true, false, 'Default layout for block showing its social attributes.', null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\block\SocialConfig', '@breeze/templates/cms/block/social/forms', 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/cms/block/social', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "cmt-block block block-max block-social block-social-regular" }', null, null ],
			[ $master->id, $master->id, 'Gallery', CmsGlobal::TEMPLATE_GALLERY, CmsGlobal::TYPE_BLOCK, null, null, true, false, 'Default layout for block showing its gallery.', null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\block\GalleryConfig', '@breeze/templates/cms/block/gallery/forms', 'cmsgears\templates\breeze\models\cms\settings\BlockSettings', '@breeze/templates/cms/block/default/forms', 'default', true, null, false, '@breeze/templates/cms/block/gallery', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "cmt-block block block-max block-gallery block-gallery-regular" }', null, null ],
			[ $master->id, $master->id, 'Slider', CmsGlobal::TEMPLATE_SLIDER, CmsGlobal::TYPE_BLOCK, null, null, true, false, 'Default layout for block showing showing slider of its gallery.', null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\block\SliderConfig', '@breeze/templates/cms/block/slider/forms', 'cmsgears\templates\breeze\models\cms\settings\BlockSettings', '@breeze/templates/cms/block/default/forms', 'default', true, null, false, '@breeze/templates/cms/block/slider', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "cmt-block block block-max block-slider block-slider-regular" }', null, null ],
			[ $master->id, $master->id, 'Attributes Slider', CmsGlobal::TEMPLATE_ATTRIBUTES_SLIDER, CmsGlobal::TYPE_BLOCK, null, null, true, false, 'Default layout for block showing slider of its attributes.', null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\block\AttributeConfig', '@breeze/templates/cms/block/attribute/forms', 'cmsgears\templates\breeze\models\cms\settings\BlockSettings', '@breeze/templates/cms/block/default/forms', 'default', true, null, false, '@breeze/templates/cms/block/attribute/slider', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "cmt-block block block-max block-attributes-slider block-attributes-slider-regular" }', null, null ],
			[ $master->id, $master->id, 'Attributes Accordian', CmsGlobal::TEMPLATE_ATTRIBUTES_ACCORDIAN, CmsGlobal::TYPE_BLOCK, null, null, true, false, 'Default layout for block showing accordian of its attributes.', null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\block\AttributeConfig', '@breeze/templates/cms/block/attribute/forms', 'cmsgears\templates\breeze\models\cms\settings\BlockSettings', '@breeze/templates/cms/block/default/forms', 'default', true, null, false, '@breeze/templates/cms/block/attribute/accordian', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "cmt-block block block-max block-attributes-accordian block-attributes-accordian-regular" }', null, null ],
			[ $master->id, $master->id, 'Elements Slider', 'elements-slider', CmsGlobal::TYPE_BLOCK, null, null, true, false, 'Default layout for block showing slider of its elements.', null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\block\ElementConfig', '@breeze/templates/cms/block/attribute/forms', 'cmsgears\templates\breeze\models\cms\settings\BlockSettings', '@breeze/templates/cms/block/default/forms', 'default', true, null, false, '@breeze/templates/cms/block/element/slider', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "cmt-block block block-max block-elements-slider block-elements-slider-regular" }', null, null ],
			[ $master->id, $master->id, 'Elements Accordian', 'elements-accordian', CmsGlobal::TYPE_BLOCK, null, null, true, false, 'Default layout for block showing accordian of its elements.', null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\block\ElementConfig', '@breeze/templates/cms/block/attribute/forms', 'cmsgears\templates\breeze\models\cms\settings\BlockSettings', '@breeze/templates/cms/block/default/forms', 'default', true, null, false, '@breeze/templates/cms/block/element/accordian', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "cmt-block block block-max block-elements-accordian block-elements-accordian-regular" }', null, null ],
			[ $master->id, $master->id, 'Elements ZigZag', 'elements-zigzag', CmsGlobal::TYPE_BLOCK, null, null, true, false, 'Default layout for blocks showing elements in zigzag arrangement.', null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\block\ElementConfig', '@breeze/templates/cms/block/attribute/forms', 'cmsgears\templates\breeze\models\cms\settings\BlockSettings', '@breeze/templates/cms/block/default/forms', 'default', true, null, false, '@breeze/templates/cms/block/element/zigzag', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "cmt-block block block-max block-elements-zigzag block-elements-zigzag-regular" }', null, '{"tsettings":{"defaultAvatar":"0","lazyAvatar":"0","resAvatar":"0","defaultBanner":"0","lazyBanner":"0","resBanner":"0","bkg":"0","fixedBkg":"0","scrollBkg":"0","parallaxBkg":"0","bkgClass":"","bkgVideo":"0","bkgHeader":"0","texture":"0","header":"1","headerIcon":"1","headerTitle":"1","headerInfo":"1","headerContent":"1","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"1","contentRaw":"","maxCover":"0","contentAvatar":"0","contentBanner":"0","contentClass":"","contentDataClass":"","styles":"","scripts":"","footer":"0","footerIcon":"0","footerIconClass":null,"footerIconUrl":"","footerTitle":"0","footerTitleData":"","footerInfo":"0","footerInfoData":"","footerContent":"0","footerContentData":"","metas":"0","metaTypes":"","metaWrapClass":"","elements":"1","elementsBeforeContent":"0","elementType":"","boxWrapClass":"data-zigzag","boxWrapper":"","boxClass":"","widgets":"0","widgetsBeforeContent":"0","widgetType":"","widgetWrapClass":"","widgetWrapper":"","widgetClass":"","purifySummary":"1","purifyContent":"1"}}' ],
			[ $master->id, $master->id, 'Form', 'form', CmsGlobal::TYPE_BLOCK, null, null, true, false, 'Default layout for block showing the form associated with it.', null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\block\FormConfig', '@breeze/templates/cms/block/attribute/forms', 'cmsgears\templates\breeze\models\cms\settings\BlockSettings', '@breeze/templates/cms/block/default/forms', 'default', true, null, false, '@breeze/templates/cms/block/form', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "cmt-block block block-max block-form block-form-regular" }', null, '{"tsettings":{"defaultAvatar":"0","lazyAvatar":"0","resAvatar":"0","defaultBanner":"0","lazyBanner":"0","resBanner":"0","bkg":"0","fixedBkg":"0","scrollBkg":"0","parallaxBkg":"0","bkgClass":"","bkgVideo":"0","bkgHeader":"0","texture":"0","header":"1","headerIcon":"1","headerTitle":"1","headerInfo":"1","headerContent":"1","headerIconUrl":"","headerClass":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"1","contentRaw":"","maxCover":"0","contentAvatar":"0","contentBanner":"0","contentClass":"","contentDataClass":"","styles":"","scripts":"","footer":"0","footerIcon":"0","footerIconClass":null,"footerIconUrl":"","footerTitle":"0","footerTitleData":"","footerInfo":"0","footerInfoData":"","footerContent":"0","footerContentData":"","metas":"0","metaTypes":"","metaWrapClass":"","elements":"0","elementsBeforeContent":"0","elementType":"","boxWrapClass":"","boxWrapper":"","boxClass":"","widgets":"0","widgetsBeforeContent":"0","widgetType":"","widgetWrapClass":"","widgetWrapper":"","widgetClass":"","purifySummary":"1","purifyContent":"1"}}' ],
			[ $master->id, $master->id, 'Announcements', 'announcements', CmsGlobal::TYPE_BLOCK, null, null, true, false, 'Announcements layout for blocks showing announcements.', null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\block\AnnouncementConfig', '@breeze/templates/cms/block/announcement/forms', 'cmsgears\templates\breeze\models\cms\settings\BlockSettings', '@breeze/templates/cms/block/default/forms', 'default', true, null, false, '@breeze/templates/cms/block/announcements', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "cmt-block block block-max block-announcements block-announcements-regular" }', null, null ],
			[ $master->id, $master->id, 'Testimonial', 'testimonial', CmsGlobal::TYPE_BLOCK, null, null, true, false, 'Testimonial layout for blocks showing testimonial form.', null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\block\TestimonialConfig', '@breeze/templates/cms/block/testimonial/forms', 'cmsgears\templates\breeze\models\cms\settings\BlockSettings', '@breeze/templates/cms/block/default/forms', 'default', true, null, false, '@breeze/templates/cms/block/testimonial', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "cmt-block block block-max block-testimonial block-testimonial-regular" }', null, null ],
			[ $master->id, $master->id, 'Testimonials', 'testimonials', CmsGlobal::TYPE_BLOCK, null, null, true, false, 'Testimonials layout for blocks showing testimonials.', null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\block\TestimonialConfig', '@breeze/templates/cms/block/testimonial/forms', 'cmsgears\templates\breeze\models\cms\settings\BlockSettings', '@breeze/templates/cms/block/default/forms', 'default', true, null, false, '@breeze/templates/cms/block/testimonials', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "cmt-block block block-max block-testimonials block-testimonials-regular" }', null, null ],
			[ $master->id, $master->id, 'Feedback', 'feedback', CmsGlobal::TYPE_BLOCK, null, null, true, false, 'Feedback layout for blocks showing feedback form.', null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\block\FeedbackConfig', '@breeze/templates/cms/block/feedback/forms', 'cmsgears\templates\breeze\models\cms\settings\BlockSettings', '@breeze/templates/cms/block/default/forms', 'default', true, null, false, '@breeze/templates/cms/block/feedback', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "cmt-block block block-max block-feedback block-feedback-regular" }', null, null ],
			[ $master->id, $master->id, 'Feedbacks', 'feedbacks', CmsGlobal::TYPE_BLOCK, null, null, true, false, 'Feedbacks layout for blocks showing feedbacks.', null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\block\FeedbackConfig', '@breeze/templates/cms/block/feedback/forms', 'cmsgears\templates\breeze\models\cms\settings\BlockSettings', '@breeze/templates/cms/block/default/forms', 'default', true, null, false, '@breeze/templates/cms/block/feedbacks', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "cmt-block block block-max block-feedbacks block-feedbacks-regular" }', null, null ],
			[ $master->id, $master->id, 'Newsletter', 'newsletter', CmsGlobal::TYPE_BLOCK, null, null, true, false, 'Newsletter layout for blocks showing newsletter form.', null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\block\NewsletterConfig', '@breeze/templates/cms/block/newsletter/forms', 'cmsgears\templates\breeze\models\cms\settings\BlockSettings', '@breeze/templates/cms/block/default/forms', 'default', true, null, false, '@breeze/templates/cms/block/newsletter', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "cmt-block block block-max block-newsletter block-newsletter-regular" }', null, null ],
			[ $master->id, $master->id, 'FoxSlider', 'foxslider', CmsGlobal::TYPE_BLOCK, null, null, true, false, 'FoxSlider layout for blocks showing slider. The block slug must be same as that of foxslider.', null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\block\FoxsliderConfig', '@breeze/templates/cms/block/foxslider/forms', 'cmsgears\templates\breeze\models\cms\settings\BlockSettings', '@breeze/templates/cms/block/default/forms', 'default', true, null, false, '@breeze/templates/cms/block/foxslider', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "block block-max block-max-buffer block-foxslider block-foxslider-regular" }', null, '{"tsettings":{"defaultAvatar":"0","lazyAvatar":"0","resAvatar":"0","defaultBanner":"0","lazyBanner":"0","resBanner":"0","bkg":"0","fixedBkg":"0","scrollBkg":"0","parallaxBkg":"0","bkgClass":"","bkgVideo":"0","bkgHeader":"0","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerInfo":"0","headerContent":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentRaw":"","maxCover":"0","contentAvatar":"0","contentBanner":"0","contentClass":"","contentDataClass":"","styles":"","scripts":"","footer":"0","footerIcon":"0","footerIconClass":null,"footerIconUrl":"","footerTitle":"0","footerTitleData":"","footerInfo":"0","footerInfoData":"","footerContent":"0","footerContentData":"","metas":"0","metaTypes":"","metaWrapClass":"","elements":"0","elementsBeforeContent":"0","elementType":"","boxWrapClass":"","boxWrapper":"","boxClass":"","widgets":"0","widgetsBeforeContent":"0","widgetType":"","widgetWrapClass":"","widgetWrapper":"","widgetClass":"","purifySummary":"1","purifyContent":"1"}}' ]
		];

		$this->batchInsert( $this->cmgPrefix . 'core_template', $columns, $templates );
	}

	private function insertWidgetTemplates() {

		$site	= $this->site;
		$master	= $this->master;

		$columns = [ 'createdBy', 'modifiedBy', 'name', 'slug', 'type', 'icon', 'title', 'active', 'frontend', 'description', 'classPath', 'dataPath', 'dataForm', 'attributesPath', 'attributesForm', 'configPath', 'configForm', 'settingsPath', 'settingsForm', 'renderer', 'fileRender', 'layout', 'layoutGroup', 'viewPath', 'view', 'createdAt', 'modifiedAt', 'htmlOptions', 'content', 'data' ];

		$templates = [
			// Text Widget - Default, Social, Address
			// Notes: Social and Address use widget attributes to manage the details
			[ $master->id, $master->id, 'Default', CoreGlobal::TEMPLATE_DEFAULT, CmsGlobal::TYPE_WIDGET, null, null, true, false, 'Default layout for widgets.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/cms/widget/default', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default" }', null, null ],
			[ $master->id, $master->id, 'Text', CoreGlobal::TEMPLATE_DEFAULT, CmsGlobal::TYPE_WIDGET, null, null, true, false, 'Default layout for widgets showing text.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/cms/widget/text', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default" }', null, null ],
			[ $master->id, $master->id, 'Social', CmsGlobal::TEMPLATE_SOCIAL, CmsGlobal::TYPE_WIDGET, null, null, true, false, 'It can be used to display social links using social attributes.', null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\widget\SocialConfig', '@breeze/templates/cms/widget/social/forms', 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/cms/widget/social', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-social" }', null, null ],
			[ $master->id, $master->id, 'Contact', CmsGlobal::TEMPLATE_CONTACT, CmsGlobal::TYPE_WIDGET, null, null, true, false, 'It can be used to display address details.', null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\widget\ContactConfig', '@breeze/templates/cms/widget/contact/forms', 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/cms/widget/contact', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-contact" }', null, null ],
			// Basic Widgets
			[ $master->id, $master->id, 'Gallery', CmsGlobal::TEMPLATE_GALLERY, CmsGlobal::TYPE_WIDGET, null, null, true, false, "Default layout for widgets showing it's gallery.", null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/cms/widget/gallery', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-gallery" }', null, null ],
			[ $master->id, $master->id, 'Slider', CmsGlobal::TEMPLATE_SLIDER, CmsGlobal::TYPE_WIDGET, null, null, true, false, "Default layout for widgets showing slider of it's gallery.", null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/cms/widget/slider', 'gallery', DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-slider" }', null, null ],
			[ $master->id, $master->id, 'Attributes Slider', CmsGlobal::TEMPLATE_ATTRIBUTES_SLIDER, CmsGlobal::TYPE_WIDGET, null, null, true, false, "Default layout for widgets showing slider of it's attributes.", null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/cms/widget/slider', 'attributes', DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default" }', null, null ],
			[ $master->id, $master->id, 'Attributes Accordian', CmsGlobal::TEMPLATE_ATTRIBUTES_ACCORDIAN, CmsGlobal::TYPE_WIDGET, null, null, true, false, "Default layout for widgets showing accordian of it's attributes.", null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/cms/widget/accordian', 'attributes', DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default" }', null, null ],
			[ $master->id, $master->id, 'Form', 'form', CmsGlobal::TYPE_WIDGET, null, null, true, false, 'It can be used to submit ajax form.', 'cmsgears\widgets\aform\AjaxFormWidget', null, null, null, null, 'cmsgears\templates\breeze\models\widget\cms\AjaxFormConfig', '@breeze/templates/widget/cms/aform/forms', 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/widget/cms/aform', 'default', DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-form" }', null, null ],
			// Embedded Widgets
			[ $master->id, $master->id, 'Element', 'element', CmsGlobal::TYPE_WIDGET, null, null, true, false, "Default layout for widgets showing Element. The widget slug must be same as that of element.", null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/cms/widget/element', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-element" }', null, null ],
			[ $master->id, $master->id, 'Block', 'block', CmsGlobal::TYPE_WIDGET, null, null, true, false, "Default layout for widgets showing Block. The widget slug must be same as that of block.", null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/cms/widget/block', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-block" }', null, null ],
			[ $master->id, $master->id, 'Menu', 'menu', CmsGlobal::TYPE_WIDGET, null, null, true, false, "Default layout for widgets showing Menu. The widget slug must be same as that of menu.", null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/cms/widget/menu', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-menu" }', null, null ],
			[ $master->id, $master->id, 'Galleria', 'galleria', CmsGlobal::TYPE_WIDGET, null, null, true, false, "Default layout for widgets showing Gallery. The widget slug must be same as that of gallery.", null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/cms/widget/gallery', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-gallery" }', null, null ],
			[ $master->id, $master->id, 'FoxSlider', 'foxslider', CmsGlobal::TYPE_WIDGET, null, null, true, false, "Default layout for widgets showing FoxSlider. The widget slug must be same as that of foxslider.", 'foxslider\widgets\FoxSliderMain', null, null, null, null, 'cmsgears\templates\breeze\models\widget\foxslider\SliderConfig', '@breeze/templates/cms/widget/foxslider/forms', 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/widget/foxslider', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-foxslider" }', null, null ],
			// Search Widget - Default
			[ $master->id, $master->id, 'Search', CmsGlobal::TEMPLATE_SEARCH, CmsGlobal::TYPE_WIDGET, null, null, true, false, 'It can be used to display page, article and post search form.', null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\widget\SearchConfig', '@breeze/templates/cms/widget/search/forms', 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/cms/widget/search', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-search" }', null, null ],
			// Author Widget - Default
			[ $master->id, $master->id, 'Author', CmsGlobal::TEMPLATE_AUTHOR, CmsGlobal::TYPE_WIDGET, null, null, true, false, 'It can be used to display author info if model supports creator or user relations. User will be given preference to Creator.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/cms/widget/author', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-author" }', null, null ],
			// Categories Widget - Default
			[ $master->id, $master->id, 'Categories', CmsGlobal::TEMPLATE_CATEGORIES, CmsGlobal::TYPE_WIDGET, null, null, true, false, 'It can be used to display categories.', null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\widget\CategoriesConfig', '@breeze/templates/cms/widget/categories/forms', 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/cms/widget/categories', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-tags" }', null, null ],
			// Tags Widget - Default
			[ $master->id, $master->id, 'Tag Cloud', CmsGlobal::TEMPLATE_TAG_CLOUD, CmsGlobal::TYPE_WIDGET, null, null, true, false, 'It can be used to display model categories and tags.', null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\config\widget\TagConfig', '@breeze/templates/cms/widget/tag/forms', 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/cms/widget/tag', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-tags" }', null, null ],
			// Archive Widget - Default
			[ $master->id, $master->id, 'Archive', CmsGlobal::TEMPLATE_ARCHIVE, CmsGlobal::TYPE_WIDGET, null, null, true, false, 'It can be used to display post and article archive list using the publish date.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/cms/widget/archive', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-archive" }', null, null ],
			// Page Widget - Default, Banner & Search
			[ $master->id, $master->id, 'Page Card', 'page-card', CmsGlobal::TYPE_WIDGET, null, null, true, false, 'It can be used to display popular, recent, and featured pages.', 'cmsgears\widgets\club\cms\PageWidget', null, null, null, null, 'cmsgears\templates\breeze\models\widget\cms\PageConfig', '@breeze/templates/widget/cms/page/forms', 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/widget/cms/page', 'card', DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-card widget-card-model widget-card-page" }', null, null ],
			[ $master->id, $master->id, 'Page Box', 'page-box', CmsGlobal::TYPE_WIDGET, null, null, true, false, 'It can be used to display related and similar pages.', 'cmsgears\widgets\club\cms\PageWidget', null, null, null, null, 'cmsgears\templates\breeze\models\widget\cms\PageConfig', '@breeze/templates/widget/cms/page/forms', 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/widget/cms/page', 'box', DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-box widget-box-model widget-box-page" }', null, null ],
			[ $master->id, $master->id, 'Page Search', 'page-search', CmsGlobal::TYPE_WIDGET, null, null, true, false, 'It can be used to search pages.', 'cmsgears\widgets\club\cms\PageWidget', null, null, null, null, 'cmsgears\templates\breeze\models\widget\cms\PageConfig', '@breeze/templates/widget/cms/page/forms', 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/widget/cms/page', 'search', DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-box widget-box-search-model widget-box-search-page" }', null, null ],
			// Article Widget - Default
			[ $master->id, $master->id, 'Article Card', 'article-card', CmsGlobal::TYPE_WIDGET, null, null, true, false, 'It can be used to display popular, recent, and featured articles.', 'cmsgears\widgets\club\cms\ArticleWidget', null, null, null, null, 'cmsgears\templates\breeze\models\widget\cms\ArticleConfig', '@breeze/templates/widget/cms/article/forms', 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/widget/cms/article', 'card', DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-card widget-card-model widget-card widget-card-article" }', null, null ],
			[ $master->id, $master->id, 'Article Box', 'article-box', CmsGlobal::TYPE_WIDGET, null, null, true, false, 'It can be used to display related and similar articles.', 'cmsgears\widgets\club\cms\ArticleWidget', null, null, null, null, 'cmsgears\templates\breeze\models\widget\cms\ArticleConfig', '@breeze/templates/widget/cms/article/forms', 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/widget/cms/article', 'box', DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-box widget-box-model widget-box-article" }', null, null ],
			[ $master->id, $master->id, 'Article Club', 'article-club', CmsGlobal::TYPE_WIDGET, null, null, true, false, 'It can be used to display popular, recent, featured, related and similar articles clubbed from multiple sites.', 'cmsgears\widgets\club\cms\ArticleWidget', null, null, null, null, 'cmsgears\templates\breeze\models\widget\cms\ArticleConfig', '@breeze/templates/widget/cms/article/forms', 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/widget/cms/article', 'club', DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-box widget-box-club widget-box-club-article" }', null, null ],
			[ $master->id, $master->id, 'Article Search', 'article-search', CmsGlobal::TYPE_WIDGET, null, null, true, false, 'It can be used to search articles.', 'cmsgears\widgets\club\cms\ArticleWidget', null, null, null, null, 'cmsgears\templates\breeze\models\widget\cms\ArticleConfig', '@breeze/templates/widget/cms/article/forms', 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/widget/cms/article', 'search', DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-box widget-box-search-model widget-box-search-article" }', null, null ],
			[ $master->id, $master->id, 'Article Home', 'article-home', CmsGlobal::TYPE_WIDGET, null, null, true, false, 'It can be used to show articles specifically on landing page.', 'cmsgears\widgets\club\cms\ArticleWidget', null, null, null, null, 'cmsgears\templates\breeze\models\widget\cms\ArticleConfig', '@breeze/templates/widget/cms/article/forms', 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/widget/cms/article', 'home', DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-box widget-box-home widget-box-home-article" }', null, null ],
			[ $master->id, $master->id, 'Article Page', 'article-page', CmsGlobal::TYPE_WIDGET, null, null, true, false, 'It can be used to show articles specifically on single post page.', 'cmsgears\widgets\club\cms\ArticleWidget', null, null, null, null, 'cmsgears\templates\breeze\models\widget\cms\ArticleConfig', '@breeze/templates/widget/cms/article/forms', 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/widget/cms/article', 'default', DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-box widget-box-page widget-box-page-article" }', null, null ],
			// Post Widget - Default
			[ $master->id, $master->id, 'Post Card', 'post-card', CmsGlobal::TYPE_WIDGET, null, null, true, false, 'It can be used to display popular, recent, and featured posts.', 'cmsgears\widgets\club\cms\PostWidget', null, null, null, null, 'cmsgears\templates\breeze\models\widget\cms\PostConfig', '@breeze/templates/widget/cms/post/forms', 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/widget/cms/post', 'card', DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-card widget-card-model widget-card-post" }', null, null ],
			[ $master->id, $master->id, 'Post Box', 'post-box', CmsGlobal::TYPE_WIDGET, null, null, true, false, 'It can be used to display related and similar posts.', 'cmsgears\widgets\club\cms\PostWidget', null, null, null, null, 'cmsgears\templates\breeze\models\widget\cms\PostConfig', '@breeze/templates/widget/cms/post/forms', 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/widget/cms/post', 'box', DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-box widget-box-model widget-box-post" }', null, null ],
			[ $master->id, $master->id, 'Post Club', 'post-club', CmsGlobal::TYPE_WIDGET, null, null, true, false, 'It can be used to display popular, recent, featured, related and similar posts clubbed from multiple sites.', 'cmsgears\widgets\club\cms\PostWidget', null, null, null, null, 'cmsgears\templates\breeze\models\widget\cms\PostConfig', '@breeze/templates/widget/cms/post/forms', 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/widget/cms/post', 'club', DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-box widget-box-club widget-box-club-post" }', null, null ],
			[ $master->id, $master->id, 'Post Search', 'post-search', CmsGlobal::TYPE_WIDGET, null, null, true, false, 'It can be used to search posts.', 'cmsgears\widgets\club\cms\PostWidget', null, null, null, null, 'cmsgears\templates\breeze\models\widget\cms\PostConfig', '@breeze/templates/widget/cms/post/forms', 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/widget/cms/post', 'search', DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-box widget-box-search-model widget-box-search-post" }', null, null ],
			[ $master->id, $master->id, 'Post Home', 'post-home', CmsGlobal::TYPE_WIDGET, null, null, true, false, 'It can be used to show posts specifically on landing page.', 'cmsgears\widgets\club\cms\PostWidget', null, null, null, null, 'cmsgears\templates\breeze\models\widget\cms\PostConfig', '@breeze/templates/widget/cms/post/forms', 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/widget/cms/post', 'home', DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-box widget-box-home widget-box-home-post" }', null, null ],
			[ $master->id, $master->id, 'Post Page', 'post-page', CmsGlobal::TYPE_WIDGET, null, null, true, false, 'It can be used to show posts specifically on single post page.', 'cmsgears\widgets\club\cms\PostWidget', null, null, null, null, 'cmsgears\templates\breeze\models\widget\cms\PostConfig', '@breeze/templates/widget/cms/post/forms', 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/widget/cms/post', 'default', DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-box widget-box-page widget-box-page-post" }', null, null ],
			// Newsletter Widget - Default
			[ $master->id, $master->id, 'Newsletter', 'newsletter', CmsGlobal::TYPE_WIDGET, null, null, true, false, 'It can be used to subscribe mailing list.', 'cmsgears\widgets\newsletter\FollowMeWidget', null, null, null, null, 'cmsgears\templates\breeze\models\widget\newsletter\NewsletterConfig', '@breeze/templates/widget/newsletter/forms', 'cmsgears\templates\breeze\models\cms\settings\WidgetSettings', '@breeze/templates/cms/widget/default/forms', 'default', true, null, false, '@breeze/templates/widget/newsletter/default', 'default', DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-newsletter" }', null, null ]
		];

		$this->batchInsert( $this->cmgPrefix . 'core_template', $columns, $templates );
	}

	private function insertSidebarTemplates() {

		$site	= $this->site;
		$master	= $this->master;

		$columns = [ 'createdBy', 'modifiedBy', 'name', 'slug', 'type', 'icon', 'title', 'active', 'frontend', 'description', 'classPath', 'dataPath', 'dataForm', 'attributesPath', 'attributesForm', 'configPath', 'configForm', 'settingsPath', 'settingsForm', 'renderer', 'fileRender', 'layout', 'layoutGroup', 'viewPath', 'view', 'createdAt', 'modifiedAt', 'htmlOptions', 'content', 'data' ];

		$templates = [
			// Sidebar - Default, Vertical, Horizontal
			[ $master->id, $master->id, 'Default', CoreGlobal::TEMPLATE_DEFAULT, CmsGlobal::TYPE_SIDEBAR, null, null, true, false, 'Default layout for sidebars.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\SidebarSettings', '@breeze/templates/cms/sidebar/default/forms', 'default', true, null, false, '@breeze/templates/cms/sidebar/default', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "sidebar-basic sidebar-default" }', null, null ],
			[ $master->id, $master->id, 'Vertical Sidebar', CmsGlobal::TEMPLATE_SIDEBAR_VERTICAL, CmsGlobal::TYPE_SIDEBAR, null, null, true, false, 'Sidebar displayed vertically on a page.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\SidebarSettings', '@breeze/templates/cms/sidebar/default/forms', 'default', true, null, false, '@breeze/templates/cms/sidebar/vertical', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "sidebar-basic sidebar-vertical" }', null, null ],
			[ $master->id, $master->id, 'Horizontal Sidebar', CmsGlobal::TEMPLATE_SIDEBAR_HORIZONTAL, CmsGlobal::TYPE_SIDEBAR, null, null, true, false, 'Sidebar displayed horizontally on a page.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\SidebarSettings', '@breeze/templates/cms/sidebar/default/forms', 'default', true, null, false, '@breeze/templates/cms/sidebar/horizontal', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "sidebar-basic sidebar-horizontal" }', null, null ]
		];

		$this->batchInsert( $this->cmgPrefix . 'core_template', $columns, $templates );
	}

	private function insertMenuTemplates() {

		$site	= $this->site;
		$master	= $this->master;

		$columns = [ 'createdBy', 'modifiedBy', 'name', 'slug', 'type', 'icon', 'title', 'active', 'frontend', 'description', 'classPath', 'dataPath', 'dataForm', 'attributesPath', 'attributesForm', 'configPath', 'configForm', 'settingsPath', 'settingsForm', 'renderer', 'fileRender', 'layout', 'layoutGroup', 'viewPath', 'view', 'createdAt', 'modifiedAt', 'htmlOptions', 'content', 'data' ];

		$templates = [
			// Menu - Default, Vertical, Horizontal
			[ $master->id, $master->id, 'Default', CoreGlobal::TEMPLATE_DEFAULT, CmsGlobal::TYPE_MENU, null, null, true, false, 'Default layout for menus.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\MenuSettings', '@breeze/templates/cms/menu/default/forms', 'default', true, null, false, '@breeze/templates/cms/menu/default', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "nav nav-default" }', null, null ],
			[ $master->id, $master->id, 'Vertical Menu', CmsGlobal::TEMPLATE_MENU_VERTICAL, CmsGlobal::TYPE_MENU, null, null, true, false, 'Vertical menu.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\MenuSettings', '@breeze/templates/cms/menu/default/forms', 'default', true, null, false, '@breeze/templates/cms/menu/vertical', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "vnav nav-vertical" }', null, null ],
			[ $master->id, $master->id, 'Horizontal Menu', CmsGlobal::TEMPLATE_MENU_HORIZONTAL, CmsGlobal::TYPE_MENU, null, null, true, false, 'Horizontal Menu.', null, null, null, null, null, null, null, 'cmsgears\templates\breeze\models\cms\settings\MenuSettings', '@breeze/templates/cms/menu/default/forms', 'default', true, null, false, '@breeze/templates/cms/menu/horizontal', null, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "nav nav-horizontal" }', null, null ]
		];

		$this->batchInsert( $this->cmgPrefix . 'core_template', $columns, $templates );
	}

    public function down() {

        echo "m180610_100000_breeze_cms will be deleted with m160621_014408_core.\n";

        return true;
    }

}
