<?php
/**
 * This file is part of CMSGears Framework. Please view License file distributed
 * with the source code for license details.
 *
 * @link https://www.cmsgears.org/
 * @copyright Copyright (c) 2015 VulpineCode Technologies Pvt. Ltd.
 */

// CMG Imports
use cmsgears\core\common\config\CoreGlobal;
use cmsgears\cms\common\config\CmsGlobal;
use cmsgears\subscription\common\config\SubscriptionGlobal;

use cmsgears\core\common\models\entities\ObjectData;
use cmsgears\core\common\models\entities\Site;
use cmsgears\core\common\models\entities\Template;
use cmsgears\core\common\models\entities\User;
use cmsgears\cms\common\models\entities\Page;
use cmsgears\cms\common\models\entities\Widget;

use cmsgears\core\common\utilities\DateUtil;

/**
 * The breeze cms migration inserts the default objects.
 *
 * @since 1.0.0
 */
class m190725_100100_breeze_subscription_data extends \cmsgears\core\common\base\Migration {

	// Public variables

	// Private Variables

	private $cmgPrefix;

	private $site;

	private $master;

	public function init() {

		// Table prefix
		$this->cmgPrefix = Yii::$app->migration->cmgPrefix;

		$this->site		= Site::findBySlug( CoreGlobal::SITE_MAIN );
		$this->master	= User::findByUsername( Yii::$app->migration->getSiteMaster() );

		Yii::$app->core->setSite( $this->site );
	}

    public function up() {

		$this->insertPages();
		$this->configurePageTemplates();

		$this->insertWidgets();
		$this->insertWidgetMappings();
    }

	/**
	 * Pages
	 */
	private function insertPages() {

		$master	= $this->master;

		$columns = [ 'createdBy', 'modifiedBy', 'name', 'slug', 'type', 'icon', 'description', 'createdAt', 'modifiedAt', 'content', 'data' ];

		$models = [
			// Default - Pages
		];

		$this->batchInsert( $this->cmgPrefix . 'cms_page', $columns, $models );
	}

	private function configurePageTemplates() {

		// Templates
		$searchTemplate = Template::findGlobalBySlugType( CmsGlobal::TEMPLATE_SEARCH, CmsGlobal::TYPE_PAGE );
		$plansTemplate	= Template::findGlobalBySlugType( SubscriptionGlobal::TEMPLATE_PLANS, CmsGlobal::TYPE_PAGE );

		// Pages
		$searchPlansPage	= Page::findBySlugType( SubscriptionGlobal::PAGE_SEARCH_PLANS, CmsGlobal::TYPE_PAGE );
		$plansPage			= Page::findBySlugType( SubscriptionGlobal::PAGE_PLANS, CmsGlobal::TYPE_PAGE );

		$this->update( $this->cmgPrefix . 'cms_model_content', [ 'templateId' => $searchTemplate->id ], "id=$searchPlansPage->id" );
		$this->update( $this->cmgPrefix . 'cms_model_content', [ 'templateId' => $plansTemplate->id ], "id=$plansPage->id" );
	}

	private function insertWidgets() {

		$site	= $this->site;
		$master	= $this->master;

		$status	= ObjectData::STATUS_ACTIVE;
		$vis	= ObjectData::VISIBILITY_PUBLIC;

		$searchTemplate = Template::findGlobalBySlugType( CmsGlobal::TEMPLATE_SEARCH, CmsGlobal::TYPE_WIDGET );

		$plancTemplate	= Template::findGlobalBySlugType( 'subscription-plan-card', CmsGlobal::TYPE_WIDGET );
		$planbTemplate	= Template::findGlobalBySlugType( 'subscription-plan-box', CmsGlobal::TYPE_WIDGET );
		$planbcTemplate	= Template::findGlobalBySlugType( 'subscription-plan-club', CmsGlobal::TYPE_WIDGET );
		$plansTemplate	= Template::findGlobalBySlugType( 'subscription-plan-search', CmsGlobal::TYPE_WIDGET );
		$planhTemplate	= Template::findGlobalBySlugType( 'subscription-plan-home', CmsGlobal::TYPE_WIDGET );

		$categoriesTemplate	= Template::findGlobalBySlugType( 'categories', CmsGlobal::TYPE_WIDGET );

		$columns = [ 'siteId', 'templateId', 'avatarId', 'bannerId', 'videoId', 'galleryId', 'createdBy', 'modifiedBy', 'name', 'slug', 'type', 'icon', 'texture', 'title', 'description', 'classPath', 'link', 'status', 'visibility', 'order', 'pinned', 'featured', 'shared', 'createdAt', 'modifiedAt', 'htmlOptions', 'summary', 'content', 'data', 'gridCache', 'gridCacheValid', 'gridCachedAt' ];

		$models = [
			// Group Widgets
			[ $site->id, $searchTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Search Subscription Plan Tool', 'search-subs-plan-tool', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Search Subscription Plans', 'It filters pages using the keywords.', NULL, NULL, 16000, 1500, 0, 0, 0, 1, DateUtil::getDateTime(), DateUtil::getDateTime(), '{ "class": "widget widget-basic widget-default widget-box widget-box-search" }', NULL, NULL, '{"config":{"searchUrl":"blog","searchParam":"keywords"},"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"1","headerIcon":"0","headerTitle":"1","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"1","contentClass":"","contentDataClass":"","styles":"","scripts":"","metas":"0","metaType":"","metaWrapClass":""}}', NULL, 0, NULL ],
			[ $site->id, $plansTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Search Subscription Plans', 'search-subs-plans', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Search Subscription Plans', 'It search Subscription Plans published on all sites.', NULL, NULL, 16000, 1500, 0, 0, 0, 1, DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"box-model-search-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-model-search box-subs-plan-search box-subs-plan-search-default col col12x4\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget widget-basic widget-default widget-box widget-box-search-model widget-box-search-subs-plan\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"blog","route":"","pagination":"1","paging":"1","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"12","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"250","excludeMain":"0","siteModels":"0","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}', NULL, 0, NULL ],
			[ $site->id, $plansTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Author Subscription Plans', 'author-subs-plans', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Author Subscription Plans', 'It search the author Subscription Plans published on all sites.', NULL, NULL, 16000, 1500, 0, 0, 0, 1, DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"box-model-search-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-model-search box-subs-plan-search box-subs-plan-search-author col col12x4\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget widget-basic widget-default widget-box widget-box-search-model widget-box-search-subs-plan widget-box-search-author\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"blog","route":"","pagination":"1","paging":"1","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"12","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"250","excludeMain":"0","siteModels":"0","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}', NULL, 0, NULL ],
			[ $site->id, $plansTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Archive Subscription Plans', 'archive-subs-plans', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Archive Subscription Plans', 'It shows the archive Subscription Plans according to selected month and published on all sites.', NULL, NULL, 16000, 1500, 0, 0, 0, 1, DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"box-model-search-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-model-search box-subs-plan-search box-subs-plan-search-archive col col12x4\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget widget-basic widget-default widget-box widget-box-search-model widget-box-search-subs-plan widget-box-search-archive\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"blog","route":"","pagination":"1","paging":"1","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"12","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"250","excludeMain":"0","siteModels":"0","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}', NULL, 0, NULL ],
			[ $site->id, $plancTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Recent Subscription Plans', 'recent-subs-plans', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Recent Subscription Plans', 'It shows the recent Subscription Plans published on all sites.', NULL, NULL, 16000, 1500, 0, 0, 0, 1, DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"1","headerIcon":"0","headerTitle":"1","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"card-model-wrap\" }","singleOptions":"{ \"class\": \"card card-default card-model card-subs-plan card-recent card-recent-subs-plan\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget widget-basic widget-default widget-card widget-card-model widget-card-subs-plan widget-card-recent widget-card-recent-subs-plan\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"blog","route":"","pagination":"0","paging":"0","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"5","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"120","excludeMain":"0","siteModels":"0","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}', NULL, 0, NULL ],
			[ $site->id, $plancTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Popular Subscription Plans', 'popular-subs-plans', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Popular Subscription Plans', 'It shows the popular Subscription Plans published on all sites.', NULL, NULL, 16000, 1500, 0, 0, 0, 1, DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"1","headerIcon":"0","headerTitle":"1","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"card-model-wrap\" }","singleOptions":"{ \"class\": \"card card-default card-model card-subs-plan card-popular card-popular-subs-plan\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"popular","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget widget-basic widget-default widget-card widget-card-model widget-card-subs-plan widget-card-popular widget-card-popular-subs-plan\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"blog","route":"","pagination":"0","paging":"0","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"5","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"120","excludeMain":"0","siteModels":"0","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}', NULL, 0, NULL ],
			[ $site->id, $plancTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Featured Subscription Plans', 'featured-subs-plans', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Popular Subscription Plans', 'It shows the featured Subscription Plans published on all sites.', NULL, NULL, 16000, 1500, 0, 0, 0, 1, DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"1","headerIcon":"0","headerTitle":"1","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"card-model-wrap\" }","singleOptions":"{ \"class\": \"card card-default card-model card-subs-plan card-featured card-featured-subs-plan\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"featured","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget widget-basic widget-default widget-card widget-card-model widget-card-subs-plan widget-card-featured widget-card-featured-subs-plan\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"blog","route":"","pagination":"0","paging":"0","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"5","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"120","excludeMain":"0","siteModels":"0","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}', NULL, 0, NULL ],
			[ $site->id, $planbTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Related Subscription Plans', 'related-subs-plans', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Popular Subscription Plans', 'It shows the Subscription Plans published by same author on all sites.', NULL, NULL, 16000, 1500, 0, 0, 0, 1, DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"route":"","allPath":"all","singlePath":"single","wrapperOptions":"{ \"class\": \"box-model-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-model box-subs-plan col col12x3\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"related","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":"0","tagParam":"0","wrap":"1","options":"{ \"class\": \"widget widget-basic widget-default widget-box widget-box-model widget-box-subs-plan widget-box-related widget-box-related-subs-plan\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","showAllPath":"0","pagination":"0","paging":"0","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"4","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"180","excludeMain":"0","siteModels":"0","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}', NULL, 0, NULL ],
			[ $site->id, $planhTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Home Subscription Plans', 'home-subs-plans', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Home Subscription Plans', 'It shows Subscription Plans published on all sites on landing page.', NULL, NULL, 16000, 1500, 0, 0, 0, 1, DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"route":"","allPath":"all","singlePath":"single","wrapperOptions":"{ \"class\": \"box-home-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-home box-home-subs-plan col col12x4\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":"0","tagParam":"0","wrap":"1","options":"{ \"class\": \"widget widget-basic widget-default widget-box widget-box-home widget-box-home-subs-plan\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","showAllPath":"0","pagination":"1","paging":"1","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"12","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"250","excludeMain":"0","siteModels":"0","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}', NULL, 0, NULL ],
			[ $site->id, $planbcTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Multisite Subscription Plans', 'multisite-subs-plans', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Multisite Subscription Plans', 'It shows the Subscription Plans published on all sites in site group.', NULL, NULL, 16000, 1500, 0, 0, 0, 1, DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"route":"","allPath":"all","singlePath":"single","wrapperOptions":"{ \"class\": \"box-model-wrap\" }","singleOptions":"{ \"class\": \"box box-default box-model box-subs-plan\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":"0","tagParam":"0","wrap":"1","options":"{ \"class\": \"widget widget-basic widget-default widget-box widget-box-club widget-box-club-subs-plan\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","showAllPath":"0","pagination":"0","paging":"0","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"4","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"180","excludeMain":"0","siteModels":"0","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}', NULL, 0, NULL ],
			[ $site->id, $plansTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Search Site Subscription Plans', 'search-site-subs-plans', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Search Subscription Plans', 'It search Subscription Plans published on active site.', NULL, NULL, 16000, 1500, 0, 0, 0, 1, DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"box-model-search-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-model-search box-subs-plan-search box-subs-plan-search-default col col12x4\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget widget-basic widget-default widget-box widget-box-search-model widget-box-search-subs-plan\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"blog","route":"blog","pagination":"1","paging":"1","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"12","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"250","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}', NULL, 0, NULL ],
			[ $site->id, $plansTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Author Site Subscription Plans', 'author-site-subs-plans', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Author Subscription Plans', 'It shows the author Subscription Plans published on active site.', NULL, NULL, 16000, 1500, 0, 0, 0, 1, DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"box-model-search-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-model-search box-subs-plan-search box-subs-plan-search-author col col12x4\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget widget-basic widget-default widget-box widget-box-search-model widget-box-search-subs-plan widget-box-search-author\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"blog","route":"","pagination":"1","paging":"1","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"12","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"250","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}', NULL, 0, NULL ],
			[ $site->id, $plansTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Archive Site Subscription Plans', 'archive-site-subs-plans', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Archive Subscription Plans', 'It shows the archive Subscription Plans according to selected month and published on active site.', NULL, NULL, 16000, 1500, 0, 0, 0, 1, DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"box-model-search-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-model-search box-subs-plan-search box-subs-plan-search-archive col col12x4\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget widget-basic widget-default widget-box widget-box-search-model widget-box-search-subs-plan widget-box-search-archive\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"blog","route":"","pagination":"1","paging":"1","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"12","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"250","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}', NULL, 0, NULL ],
			[ $site->id, $plancTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Recent Site Subscription Plans', 'recent-site-subs-plans', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Recent Subscription Plans', 'It shows the recent Subscription Plans published on active site.', NULL, NULL, 16000, 1500, 0, 0, 0, 1, DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"1","headerIcon":"0","headerTitle":"1","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"card-model-wrap\" }","singleOptions":"{ \"class\": \"card card-default card-model card-subs-plan card-recent card-recent-subs-plan\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget widget-basic widget-default widget-card widget-card-model widget-card-subs-plan widget-card-recent widget-card-recent-subs-plan\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"blog","route":"","pagination":"0","paging":"0","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"5","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"120","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}', NULL, 0, NULL ],
			[ $site->id, $plancTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Popular Site Subscription Plans', 'popular-site-subs-plans', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Popular Subscription Plans', 'It shows the popular Subscription Plans published on active site.', NULL, NULL, 16000, 1500, 0, 0, 0, 1, DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"1","headerIcon":"0","headerTitle":"1","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"card-model-wrap\" }","singleOptions":"{ \"class\": \"card card-default card-model card-subs-plan card-popular card-popular-subs-plan\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"popular","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget widget-basic widget-default widget-card widget-card-model widget-card-subs-plan widget-card-popular widget-card-popular-subs-plan\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"blog","route":"","pagination":"0","paging":"0","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"5","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"120","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}', NULL, 0, NULL ],
			[ $site->id, $plancTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Featured Site Subscription Plans', 'featured-site-subs-plans', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Featured Subscription Plans', 'It shows the featured Subscription Plans published on active site.', NULL, NULL, 16000, 1500, 0, 0, 0, 1, DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"1","headerIcon":"0","headerTitle":"1","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"card-model-wrap\" }","singleOptions":"{ \"class\": \"card card-default card-model card-subs-plan card-featured card-featured-subs-plan\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"featured","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget widget-basic widget-default widget-card widget-card-model widget-card-subs-plan widget-card-featured widget-card-featured-subs-plan\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"blog","route":"","pagination":"0","paging":"0","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"5","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"120","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}', NULL, 0, NULL ],
			[ $site->id, $planbTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Related Site Subscription Plans', 'related-site-subs-plans', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Related Subscription Plans', 'It shows the related Subscription Plans published on active site.', NULL, NULL, 16000, 1500, 0, 0, 0, 1, DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"1","headerIcon":"0","headerTitle":"1","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"card-model-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-model box-subs-plan box-related box-related-subs-plan col col14\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"related","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget widget-basic widget-default widget-box widget-box-model widget-box-subs-plan widget-box-related widget-box-related-subs-plan\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"blog","route":"","pagination":"0","paging":"0","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"5","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"120","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}', NULL, 0, NULL ],
			[ $site->id, $planbTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Similar Subscription Plans', 'similar-subs-plans', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Similar Subscription Plans', 'It shows the similar Subscription Plans having same category or tag.', NULL, NULL, 16000, 1500, 0, 0, 0, 1, DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"route":"","allPath":"all","singlePath":"single","wrapperOptions":"{ \"class\": \"box-model-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-model box-subs-plan box-similar box-similar-subs-plan col col14\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"similar","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":"0","tagParam":"0","wrap":"1","options":"{ \"class\": \"widget widget-basic widget-default widget-box widget-box-model widget-box-subs-plan widget-box-similar widget-box-similar-subs-plan\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","showAllPath":"0","pagination":"0","paging":"0","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"4","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"180","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}', NULL, 0, NULL ],
			[ $site->id, $plansTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Category Subscription Plans', 'category-subs-plans', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Category Subscription Plans', 'It search the category Subscription Plans published on active site.', NULL, NULL, 16000, 1500, 0, 0, 0, 1, DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"box-model-search-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-model-search box-subs-plan-search box-subs-plan-search-category col col12x4\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"category","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":true,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget widget-basic widget-default widget-box widget-box-category widget-box-category-subs-plan\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"blog","route":"","pagination":"1","paging":"1","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"12","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"250","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}', NULL, 0, NULL ],
			[ $site->id, $plansTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Tag Subscription Plans', 'tag-subs-plans', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Tag Subscription Plans', 'It search the tag Subscription Plans published on active site.', NULL, NULL, 16000, 1500, 0, 0, 0, 1, DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"box-model-search-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-model-search box-subs-plan-search box-subs-plan-search-tag col col12x4\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"tag","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":true,"wrap":"1","options":"{ \"class\": \"widget widget-basic widget-default widget-box widget-box-tag widget-box-tag-subs-plan\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"blog","route":"","pagination":"1","paging":"1","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"12","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"250","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}', NULL, 0, NULL ],
			[ $site->id, $categoriesTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Subscription Plan Categories', 'subscription-categories', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Subscription Plan Categories', 'It shows the list of Subscription Plan categories.', NULL, NULL, 16000, 1500, 0, 0, 0, 1, DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"route":"","allPath":"all","singlePath":"single","wrapperOptions":"{ \"class\": \"box-model-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-model box-subs-plan col col12x3\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"similar","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":"0","tagParam":"0","wrap":"1","options":"{ \"class\": \"widget widget-basic widget-default widget-box widget-box-categories\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","showAllPath":"0","pagination":"0","paging":"0","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"4","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"180","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}', NULL, 0, NULL ]
		];

		$this->batchInsert( $this->cmgPrefix . 'core_object', $columns, $models );
	}

	private function insertWidgetMappings() {

		$searchPlansPage	= Page::findBySlugType( SubscriptionGlobal::PAGE_SEARCH_PLANS, CmsGlobal::TYPE_PAGE );
		$plansPage			= Page::findBySlugType( SubscriptionGlobal::PAGE_PLANS, CmsGlobal::TYPE_PAGE );

		$searchPlansWidget = Widget::findBySlugType( 'search-site-subs-plans', CmsGlobal::TYPE_WIDGET );

		$columns = [ 'modelId', 'parentId', 'parentType', 'type', 'order', 'active', 'pinned', 'featured', 'nodes' ];

		$mappings = [
			[ $searchPlansWidget->id, $searchPlansPage->id, 'page', CmsGlobal::TYPE_WIDGET, 0, 1, 0, 0, NULL ],
			[ $searchPlansWidget->id, $plansPage->id, 'page', CmsGlobal::TYPE_WIDGET, 0, 1, 0, 0, NULL ]
		];

		$this->batchInsert( $this->cmgPrefix . 'core_model_object', $columns, $mappings );
	}

    public function down() {

        echo "m190725_100100_breeze_subscription_data will be deleted with m160621_014408_core.\n";

        return true;
    }

}
