<?php
/**
 * This file is part of CMSGears Framework. Please view License file distributed
 * with the source code for license details.
 *
 * @link https://www.cmsgears.org/
 * @copyright Copyright (c) 2015 VulpineCode Technologies Pvt. Ltd.
 */

// CMG Imports
use cmsgears\core\common\config\CoreGlobal;
use cmsgears\cms\common\config\CmsGlobal;
use cmsgears\career\common\config\CareerGlobal;

use cmsgears\core\common\models\entities\ObjectData;
use cmsgears\core\common\models\entities\Site;
use cmsgears\core\common\models\entities\Template;
use cmsgears\core\common\models\entities\User;
use cmsgears\cms\common\models\entities\Page;
use cmsgears\cms\common\models\entities\Widget;

use cmsgears\core\common\utilities\DateUtil;

/**
 * The breeze cms migration inserts the default objects.
 *
 * @since 1.0.0
 */
class m180613_100100_breeze_career_data extends \cmsgears\core\common\base\Migration {

	// Public variables

	// Private Variables

	private $cmgPrefix;

	private $site;

	private $master;

	public function init() {

		// Table prefix
		$this->cmgPrefix = Yii::$app->migration->cmgPrefix;

		$this->site		= Site::findBySlug( CoreGlobal::SITE_MAIN );
		$this->master	= User::findByUsername( Yii::$app->migration->getSiteMaster() );

		Yii::$app->core->setSite( $this->site );
	}

    public function up() {

		$this->insertPages();
		$this->configurePageTemplates();

		$this->insertWidgets();
		$this->insertWidgetMappings();
    }

	/**
	 * Pages
	 */
	private function insertPages() {

		$master	= $this->master;

		$columns = [ 'createdBy', 'modifiedBy', 'name', 'slug', 'type', 'icon', 'description', 'createdAt', 'modifiedAt', 'content', 'data' ];

		$models = [
			// Default - Pages
		];

		$this->batchInsert( $this->cmgPrefix . 'cms_page', $columns, $models );
	}

	/**
	 * Page - Template Mappings
	 */
	private function configurePageTemplates() {

		// Templates
		$searchTemplate = Template::findGlobalBySlugType( CmsGlobal::TEMPLATE_SEARCH, CmsGlobal::TYPE_PAGE );

		// Pages
		$jobsPage		= Page::findBySlugType( CareerGlobal::PAGE_SEARCH_JOBS, CmsGlobal::TYPE_PAGE );
		$internshipPage	= Page::findBySlugType( CareerGlobal::PAGE_SEARCH_INTERNSHIP, CmsGlobal::TYPE_PAGE );

		$this->update( $this->cmgPrefix . 'cms_model_content', [ 'templateId' => $searchTemplate->id ], "id=$jobsPage->id" );
		$this->update( $this->cmgPrefix . 'cms_model_content', [ 'templateId' => $searchTemplate->id ], "id=$internshipPage->id" );
	}

	private function insertWidgets() {

		$site	= $this->site;
		$master	= $this->master;
		$status	= ObjectData::STATUS_ACTIVE;
		$vis	= ObjectData::VISIBILITY_PUBLIC;

		$jobcTemplate	= Template::findGlobalBySlugType( 'job-card', CmsGlobal::TYPE_WIDGET );
		$jobbTemplate	= Template::findGlobalBySlugType( 'job-box', CmsGlobal::TYPE_WIDGET );
		$jobbcTemplate	= Template::findGlobalBySlugType( 'job-club', CmsGlobal::TYPE_WIDGET );
		$jobsTemplate	= Template::findGlobalBySlugType( 'job-search', CmsGlobal::TYPE_WIDGET );
		$jobhTemplate	= Template::findGlobalBySlugType( 'job-home', CmsGlobal::TYPE_WIDGET );

		$internshipcTemplate	= Template::findGlobalBySlugType( 'internship-card', CmsGlobal::TYPE_WIDGET );
		$internshipbTemplate	= Template::findGlobalBySlugType( 'internship-box', CmsGlobal::TYPE_WIDGET );
		$internshipbcTemplate	= Template::findGlobalBySlugType( 'internship-club', CmsGlobal::TYPE_WIDGET );
		$internshipsTemplate	= Template::findGlobalBySlugType( 'internship-search', CmsGlobal::TYPE_WIDGET );
		$internshiphTemplate	= Template::findGlobalBySlugType( 'internship-home', CmsGlobal::TYPE_WIDGET );

		$columns = [ 'siteId', 'templateId', 'avatarId', 'bannerId', 'videoId', 'galleryId', 'createdBy', 'modifiedBy', 'name', 'slug', 'type', 'icon', 'texture', 'title', 'description', 'classPath', 'link', 'status', 'visibility', 'order', 'pinned', 'featured', 'createdAt', 'modifiedAt', 'htmlOptions', 'summary', 'content', 'data' ];

		$models = [
			// Job Widgets
			[ $site->id, $jobsTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Search Jobs', 'search-jobs', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Search Jobs', 'It search jobs published on all sites.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"box-page-search-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-page-search col col12x4 row\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget-basic widget-box widget-box-search widget-box-search-job\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"single","route":"","pagination":"1","paging":"1","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"12","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"250","excludeMain":"0","siteModels":"0","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $jobsTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Author Jobs', 'author-jobs', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Author Jobs', 'It search the author jobs published on all sites.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"box-page-search-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-page-search col col12x4 row\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget-basic widget-box widget-box-search widget-box-search-author widget-box-search-job\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"single","route":"","pagination":"1","paging":"1","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"12","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"250","excludeMain":"0","siteModels":"0","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $jobsTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Archive Jobs', 'archive-jobs', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Archive Jobs', 'It shows the archive jobs according to selected month and published on all sites.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"box-page-search-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-page-search col col12x4 row\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget-basic widget-box widget-box-search widget-box-search-archive widget-box-search-job\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"single","route":"","pagination":"1","paging":"1","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"12","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"250","excludeMain":"0","siteModels":"0","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $jobcTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Recent Jobs', 'recent-jobs', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Recent Jobs', 'It shows the recent jobs published on all sites.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"1","headerIcon":"0","headerTitle":"1","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"card-page-wrap\" }","singleOptions":"{ \"class\": \"card card-default card-page\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget-basic widget-card widget-card-recent widget-card-job\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"single","route":"","pagination":"0","paging":"0","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"5","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"120","excludeMain":"0","siteModels":"0","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $jobcTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Popular Jobs', 'popular-jobs', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Popular Jobs', 'It shows the popular jobs published on all sites.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"1","headerIcon":"0","headerTitle":"1","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"card-page-wrap\" }","singleOptions":"{ \"class\": \"card card-default card-page\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"popular","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget-basic widget-card widget-card-popular widget-card-job\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"single","route":"","pagination":"0","paging":"0","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"5","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"120","excludeMain":"0","siteModels":"0","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $jobbTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Related Jobs', 'related-jobs', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Popular Jobs', 'It shows the jobs published by same author on all sites.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"route":"","allPath":"all","singlePath":"single","wrapperOptions":"{ \"class\": \"box-page-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-page col col12x3\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"related","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":"0","tagParam":"0","wrap":"1","options":"{ \"class\": \"widget-basic widget-box widget-box-related widget-box-job\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","showAllPath":"0","pagination":"0","paging":"0","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"4","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"180","excludeMain":"0","siteModels":"0","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $jobhTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Home Jobs', 'home-jobs', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Home Jobs', 'It shows Jobs published on all sites on landing page.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"route":"","allPath":"all","singlePath":"single","wrapperOptions":"{ \"class\": \"box-home-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-home col col12x4 row\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":"0","tagParam":"0","wrap":"1","options":"{ \"class\": \"widget-basic widget-box widget-box-home widget-box-home-job\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","showAllPath":"0","pagination":"1","paging":"1","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"12","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"250","excludeMain":"0","siteModels":"0","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $jobbcTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Multisite Jobs', 'multisite-jobs', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Multisite Jobs', 'It shows the jobs published on all sites in site group.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"route":"","allPath":"all","singlePath":"single","wrapperOptions":"{ \"class\": \"box-page-wrap\" }","singleOptions":"{ \"class\": \"box box-default box-page\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":"0","tagParam":"0","wrap":"1","options":"{ \"class\": \"widget-basic widget-box widget-box-club widget-box-club-job\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","showAllPath":"0","pagination":"0","paging":"0","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"4","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"180","excludeMain":"0","siteModels":"0","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $jobsTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Search Site Jobs', 'search-site-jobs', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Search Jobs', 'It search jobs published on active site.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"box-page-search-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-page-search col col12x4 row\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget-basic widget-box widget-box-search widget-box-search-job\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"single","route":"","pagination":"1","paging":"1","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"12","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"250","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $jobsTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Author Site Jobs', 'author-site-jobs', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Author Jobs', 'It shows the author jobs published on active site.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"box-page-search-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-page-search col col12x4 row\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget-basic widget-box widget-box-search widget-box-search-author widget-box-search-job\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"single","route":"","pagination":"1","paging":"1","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"12","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"250","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $jobsTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Archive Site Jobs', 'archive-site-jobs', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Archive Jobs', 'It shows the archive jobs according to selected month and published on active site.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"box-page-search-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-page-search col col12x4 row\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget-basic widget-box widget-box-search widget-box-search-archive widget-box-search-job\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"single","route":"","pagination":"1","paging":"1","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"12","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"250","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $jobcTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Recent Site Jobs', 'recent-site-jobs', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Recent Jobs', 'It shows the recent jobs published on active site.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"1","headerIcon":"0","headerTitle":"1","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"card-page-wrap\" }","singleOptions":"{ \"class\": \"card card-default card-page\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget-basic widget-card widget-card-recent widget-card-job\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"single","route":"","pagination":"0","paging":"0","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"5","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"120","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $jobcTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Popular Site Jobs', 'popular-site-jobs', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Popular Jobs', 'It shows the popular jobs published on active site.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"1","headerIcon":"0","headerTitle":"1","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"card-page-wrap\" }","singleOptions":"{ \"class\": \"card card-default card-page\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"popular","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget-basic widget-card widget-card-popular widget-card-job\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"single","route":"","pagination":"0","paging":"0","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"5","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"120","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $jobbTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Related Site Jobs', 'related-site-jobs', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Related Jobs', 'It shows the related jobs published on active site.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"1","headerIcon":"0","headerTitle":"1","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"card-page-wrap\" }","singleOptions":"{ \"class\": \"card card-default card-page\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"related","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget-basic widget-card widget-card-related widget-card-job\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"single","route":"","pagination":"0","paging":"0","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"5","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"120","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $jobsTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Category Jobs', 'category-jobs', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Category Jobs', 'It search the category jobs published on active site.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"box-page-search-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-page-search col col12x4 row\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"category","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget-basic widget-box widget-box-search widget-box-search-job\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"single","route":"","pagination":"1","paging":"1","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"12","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"250","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $jobsTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Tag Jobs', 'tag-jobs', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Tag Jobs', 'It search the tag Jobs published on active site.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"box-page-search-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-page-search col col12x4 row\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"tag","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget-basic widget-box widget-box-search widget-box-search-job\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"single","route":"","pagination":"1","paging":"1","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"12","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"250","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $jobbTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Similar Jobs', 'similar-jobs', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Similar Jobs', 'It shows the similar jobs having same category or tag.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"route":"","allPath":"all","singlePath":"single","wrapperOptions":"{ \"class\": \"box-page-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-page col col12x3\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"similar","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":"0","tagParam":"0","wrap":"1","options":"{ \"class\": \"widget-basic widget-box widget-box-similar widget-box-job\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","showAllPath":"0","pagination":"0","paging":"0","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"4","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"180","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			// Internship Widgets
			[ $site->id, $internshipsTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Search Internships', 'search-internships', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Search Internships', 'It search internships published on all sites.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"box-page-search-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-page-search col col12x4 row\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget-basic widget-box widget-box-search widget-box-search-internship\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"single","route":"","pagination":"1","paging":"1","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"12","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"250","excludeMain":"0","siteModels":"0","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $internshipsTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Author Internships', 'author-internships', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Author Internships', 'It search the author internships published on all sites.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"box-page-search-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-page-search col col12x4 row\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget-basic widget-box widget-box-search widget-box-search-author widget-box-search-internship\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"single","route":"","pagination":"1","paging":"1","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"12","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"250","excludeMain":"0","siteModels":"0","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $internshipsTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Archive Internships', 'archive-internships', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Archive Internships', 'It shows the archive internships according to selected month and published on all sites.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"box-page-search-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-page-search col col12x4 row\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget-basic widget-box widget-box-search widget-box-search-archive widget-box-search-internship\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"single","route":"","pagination":"1","paging":"1","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"12","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"250","excludeMain":"0","siteModels":"0","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $internshipcTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Recent Internships', 'recent-internships', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Recent Internships', 'It shows the recent internships published on all sites.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"1","headerIcon":"0","headerTitle":"1","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"card-page-wrap\" }","singleOptions":"{ \"class\": \"card card-default card-page\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget-basic widget-card widget-card-recent widget-card-internship\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"single","route":"","pagination":"0","paging":"0","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"5","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"120","excludeMain":"0","siteModels":"0","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $internshipcTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Popular Internships', 'popular-internships', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Popular Internships', 'It shows the popular internships published on all sites.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"1","headerIcon":"0","headerTitle":"1","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"card-page-wrap\" }","singleOptions":"{ \"class\": \"card card-default card-page\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"popular","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget-basic widget-card widget-card-popular widget-card-internship\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"single","route":"","pagination":"0","paging":"0","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"5","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"120","excludeMain":"0","siteModels":"0","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $internshipbTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Related Internships', 'related-internships', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Popular Internships', 'It shows the internships published by same author on all sites.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"route":"","allPath":"all","singlePath":"single","wrapperOptions":"{ \"class\": \"box-page-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-page col col12x3\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"related","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":"0","tagParam":"0","wrap":"1","options":"{ \"class\": \"widget-basic widget-box widget-box-related widget-box-internship\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","showAllPath":"0","pagination":"0","paging":"0","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"4","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"180","excludeMain":"0","siteModels":"0","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $internshiphTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Home Internships', 'home-internships', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Home Internships', 'It shows internships published on all sites on landing page.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"route":"","allPath":"all","singlePath":"single","wrapperOptions":"{ \"class\": \"box-home-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-home col col12x4 row\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":"0","tagParam":"0","wrap":"1","options":"{ \"class\": \"widget-basic widget-box widget-box-home widget-box-home-internship\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","showAllPath":"0","pagination":"1","paging":"1","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"12","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"250","excludeMain":"0","siteModels":"0","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $internshipbcTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Multisite Internships', 'multisite-internships', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Multisite Internships', 'It shows the internships published on all sites in site group.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"route":"","allPath":"all","singlePath":"single","wrapperOptions":"{ \"class\": \"box-page-wrap\" }","singleOptions":"{ \"class\": \"box box-default box-page\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":"0","tagParam":"0","wrap":"1","options":"{ \"class\": \"widget-basic widget-box widget-box-club widget-box-club-internship\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","showAllPath":"0","pagination":"0","paging":"0","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"4","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"180","excludeMain":"0","siteModels":"0","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $internshipsTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Search Site Internships', 'search-site-internships', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Search Internships', 'It search internships published on active site.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"box-page-search-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-page-search col col12x4 row\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget-basic widget-box widget-box-search widget-box-search-internship\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"single","route":"","pagination":"1","paging":"1","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"12","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"250","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $internshipsTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Author Site Internships', 'author-site-internships', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Author Internships', 'It shows the author internships published on active site.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"box-page-search-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-page-search col col12x4 row\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget-basic widget-box widget-box-search widget-box-search-author widget-box-search-internship\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"single","route":"","pagination":"1","paging":"1","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"12","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"250","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $internshipsTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Archive Site Internships', 'archive-site-internships', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Archive Internships', 'It shows the archive internships according to selected month and published on active site.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"box-page-search-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-page-search col col12x4 row\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget-basic widget-box widget-box-search widget-box-search-archive widget-box-search-internship\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"single","route":"","pagination":"1","paging":"1","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"12","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"250","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $internshipcTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Recent Site Internships', 'recent-site-internships', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Recent Internships', 'It shows the recent internships published on active site.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"1","headerIcon":"0","headerTitle":"1","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"card-page-wrap\" }","singleOptions":"{ \"class\": \"card card-default card-page\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"recent","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget-basic widget-card widget-card-recent widget-card-internship\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"single","route":"","pagination":"0","paging":"0","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"5","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"120","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $internshipcTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Popular Site Internships', 'popular-site-internships', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Popular Internships', 'It shows the popular internships published on active site.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"1","headerIcon":"0","headerTitle":"1","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"card-page-wrap\" }","singleOptions":"{ \"class\": \"card card-default card-page\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"popular","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget-basic widget-card widget-card-popular widget-card-internship\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"single","route":"","pagination":"0","paging":"0","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"5","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"120","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $internshipbTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Related Site Internships', 'related-site-internships', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Related Internships', 'It shows the related internships published on active site.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"1","headerIcon":"0","headerTitle":"1","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"card-page-wrap\" }","singleOptions":"{ \"class\": \"card card-default card-page\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"related","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget-basic widget-card widget-card-related widget-card-internship\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"single","route":"","pagination":"0","paging":"0","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"5","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"120","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $internshipsTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Category Internships', 'category-internships', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Category Internships', 'It search the category internships published on active site.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"box-page-search-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-page-search col col12x4 row\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"category","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget-basic widget-box widget-box-search widget-box-search-internship\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"single","route":"","pagination":"1","paging":"1","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"12","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"250","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $internshipsTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Tag Internships', 'tag-internships', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Tag Internships', 'It search the tag internships published on active site.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"wrapperOptions":"{ \"class\": \"box-page-search-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-page-search col col12x4 row\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"tag","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":false,"tagParam":false,"wrap":"1","options":"{ \"class\": \"widget-basic widget-box widget-box-search widget-box-search-internship\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","allPath":"all","showAllPath":"0","singlePath":"single","route":"","pagination":"1","paging":"1","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"12","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"250","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ],
			[ $site->id, $internshipbTemplate->id, NULL, NULL, NULL, NULL, $master->id, $master->id, 'Similar Internships', 'similar-internships', CmsGlobal::TYPE_WIDGET, 'icon', 'texture', 'Similar Internships', 'It shows the similar internships having same category or tag.', NULL, NULL, 16000, 1500,0,0,0,DateUtil::getDateTime(), DateUtil::getDateTime(), NULL, NULL, NULL, '{"settings":{"defaultAvatar":"0","defaultBanner":"0","bkg":"0","bkgClass":"","texture":"0","header":"0","headerIcon":"0","headerTitle":"0","headerIconUrl":"","content":"1","contentTitle":"0","contentInfo":"0","contentSummary":"0","contentData":"0","contentClass":"","contentDataClass":"","styles":"","metas":"0","metaType":"","metaWrapClass":""},"config":{"route":"","allPath":"all","singlePath":"single","wrapperOptions":"{ \"class\": \"box-page-wrap row max-cols-50\" }","singleOptions":"{ \"class\": \"box box-default box-page col col12x3\" }","excludeParams":"{\"params\": [ \"slug\" ] }","widget":"similar","texture":"","defaultBanner":"0","authorParam":"0","categoryParam":"0","tagParam":"0","wrap":"1","options":"{ \"class\": \"widget-basic widget-box widget-box-similar widget-box-internship\" }","wrapSingle":"1","singleWrapper":"div","basePath":"","showAllPath":"0","pagination":"0","paging":"0","nextLabel":"&raquo;","prevLabel":"&laquo;","limit":"4","ajaxPagination":"0","ajaxPageApp":"pagination","ajaxPageController":"page","ajaxPageAction":"getPage","ajaxUrl":"","textLimit":"180","excludeMain":"0","siteModels":"1","wrapper":"div","loadAssets":"0","templateDir":null,"template":"default","factory":true,"cache":false,"cacheDb":false,"cacheFile":false,"autoload":"0","autoloadTemplate":"autoload","autoloadApp":"autoload","autoloadController":"autoload","autoloadAction":"autoload","autoloadUrl":""}}' ]
		];

		$this->batchInsert( $this->cmgPrefix . 'core_object', $columns, $models );
	}

	private function insertWidgetMappings() {

		$searchIntern = Page::findBySlugType( 'search-internships', CmsGlobal::TYPE_PAGE );

		$searchJob = Page::findBySlugType( 'search-jobs', CmsGlobal::TYPE_PAGE );

		$searchInternWidget = Widget::findBySlugType( 'search-site-internships', CmsGlobal::TYPE_WIDGET );

		$searchJobsWidget = Widget::findBySlugType( 'search-site-jobs', CmsGlobal::TYPE_WIDGET );

		$columns = [ 'modelId', 'parentId', 'parentType', 'type', 'order', 'active', 'pinned', 'featured', 'nodes' ];

		$mappings = [
			[ $searchInternWidget->id, $searchIntern->id, 'page', CmsGlobal::TYPE_WIDGET, 0, 1, 0, 0, NULL ],
			[ $searchJobsWidget->id, $searchJob->id, 'page', CmsGlobal::TYPE_WIDGET, 0, 1, 0, 0, NULL ]
		];

		$this->batchInsert( $this->cmgPrefix . 'core_model_object', $columns, $mappings );
	}

    public function down() {

        echo "m180613_100100_breeze_career_data will be deleted with m160621_014408_core.\n";

        return true;
    }

}
